// =====================================================================
// Contenus de la borne : textes de l'interface (FR / EN / ES) et rayons.
// Les rayons suivent le plan réel du magasin (étage 0 et niveau -1).
// Pour ajouter un mot-clé, complétez la liste "keywords" du rayon voulu.
// Les accents, majuscules, pluriels simples et petites fautes sont gérés
// automatiquement (voir js/search.js).
// =====================================================================

export const LANGS = {
  fr: { speech: "fr-FR", name: "Français" },
  en: { speech: "en-GB", name: "English" },
  es: { speech: "es-ES", name: "Español" }
};

const FLOOR_NAMES = {
  fr: { "0": "l'étage 0", "-1": "le sous-sol" },
  en: { "0": "floor 0", "-1": "the basement" },
  es: { "0": "la planta 0", "-1": "el sótano" }
};

export const UI = {
  fr: {
    idleHello: "Bonjour !",
    idleTitle: "Je suis Jeanne, votre guide à la Fnac Jeanne d'Arc.",
    idleSub: "Dites-moi ce que vous cherchez, je vous montre le rayon.",
    // Trait d'union et espaces insécables (U+2011, U+202F) : la bulle est
    // étroite, sans eux la ligne se coupait sur « puis-je » et le « ? »
    // partait seul à la ligne.
    idleBubble: "Bienvenue ! En quoi puis‑je vous aider ?",
    idleCta: "Touchez l'écran pour commencer",
    greeting: "Bonjour et bienvenue à la Fnac Jeanne d'Arc ! Dites-moi ce que vous cherchez, je vous montre le rayon sur le plan.",
    switched: "Très bien, je continue en français. Que cherchez-vous ?",
    statusReady: "Posez votre question",
    statusListening: "Je vous écoute…",
    statusSpeaking: "Jeanne vous répond",
    micIdle: "Appuyez pour parler",
    micListening: "Je vous écoute… touchez pour arrêter",
    placeholder: "Ou écrivez ici : casque, PS5, iPhone…",
    send: "Envoyer",
    suggestionsTitle: "Recherches fréquentes",
    vendor: "Appeler un vendeur",
    accessibility: "Accessibilité",
    end: "Terminer",
    mapTitle: "Plan du magasin",
    floor0: "Étage 0",
    floorM1: "Sous-sol",
    youAreHere: "Vous êtes ici",
    stepEntrance: "Entrée",
    stepStairs: "Escalier",
    routeHint: "Touchez un rayon du plan pour savoir ce qu'on y trouve.",
    found: (zone, floor) => floor === "-1"
      ? `Le rayon ${zone} est au sous-sol. Prenez l'escalier vers le sous-sol, puis suivez le plan.`
      : `Le rayon ${zone} est ici, à l'étage 0. Je vous l'indique sur le plan.`,
    foundStairs: "Les LEGO, figurines POP et cartes Pokémon sont dans l'escalier qui relie l'étage 0 au sous-sol.",
    foundEntrance: "L'entrée et la sortie sont à l'étage 0, en bas du plan.",
    notFound: "Je n'ai pas trouvé ce produit. Essayez avec un autre mot, ou appelez un vendeur : il viendra vous aider.",
    hello: "Bonjour ! Quel produit cherchez-vous ?",
    thanks: "Avec plaisir ! Bonne visite à la Fnac.",
    human: "Bien sûr. Touchez « Appeler un vendeur » et un membre de l'équipe viendra vous aider.",
    otherStore: "Les livres, BD, manuels scolaires, CD, vinyles et DVD se trouvent à la Fnac Wilson, 16 allées Franklin-Roosevelt, près de Jean-Jaurès. Ici, à la Fnac Jeanne d'Arc, nous sommes spécialisés dans la technique.",
    otherStoreWhat: "Livres, BD, manuels scolaires, CD, vinyles, DVD",
    otherStoreNear: "Près de Jean-Jaurès",
    otherStoreClose: "Retour au plan",
    didYouMean: (word) => `Vous voulez dire « ${word} » ? `,
    vendorConfirm: (zone) => zone
      ? `C'est noté : un vendeur du rayon ${zone} a été prévenu.`
      : "C'est noté : un vendeur a été prévenu et arrive.",
    vendorToast: (zone) => zone ? `Vendeur prévenu · rayon ${zone}` : "Vendeur prévenu",
    micUnsupported: "Le micro n'est pas disponible sur cet appareil. Vous pouvez écrire votre question.",
    micError: "Je n'ai pas bien entendu. Réessayez, ou écrivez votre question.",
    micDenied: "Le micro est bloqué. Autorisez-le dans le navigateur, ou écrivez votre question.",
    idleWarnTitle: "Vous êtes toujours là ?",
    idleWarnBody: (s) => `Retour à l'accueil dans ${s} s.`,
    idleWarnButton: "Je continue",
    floorName: (f) => FLOOR_NAMES.fr[f]
  },
  en: {
    idleHello: "Hello!",
    idleTitle: "I'm Jeanne, your guide at Fnac Jeanne d'Arc.",
    idleSub: "Tell me what you're looking for and I'll show you where it is.",
    idleBubble: "Welcome! How can I help you?",
    idleCta: "Touch the screen to start",
    greeting: "Hello and welcome to Fnac Jeanne d'Arc! Tell me what you're looking for and I'll show you the section on the map.",
    switched: "Sure, let's continue in English. What are you looking for?",
    statusReady: "Ask me anything",
    statusListening: "Listening…",
    statusSpeaking: "Jeanne is answering",
    micIdle: "Tap to talk",
    micListening: "Listening… tap to stop",
    placeholder: "Or type here: headphones, PS5, iPhone…",
    send: "Send",
    suggestionsTitle: "Popular searches",
    vendor: "Call a staff member",
    accessibility: "Accessibility",
    end: "Finish",
    mapTitle: "Store map",
    floor0: "Floor 0",
    floorM1: "Basement",
    youAreHere: "You are here",
    stepEntrance: "Entrance",
    stepStairs: "Stairs",
    routeHint: "Tap a section on the map to see what's there.",
    found: (zone, floor) => floor === "-1"
      ? `${zone} is in the basement. Take the stairs down, then follow the map.`
      : `${zone} is right here on floor 0. I'm showing it on the map.`,
    foundStairs: "LEGO, POP figures and Pokémon cards are in the staircase between floor 0 and the basement.",
    foundEntrance: "The entrance and exit are on floor 0, at the bottom of the map.",
    notFound: "I couldn't find that product. Try another word, or call a staff member who will come and help you.",
    hello: "Hello! What product are you looking for?",
    thanks: "You're welcome! Enjoy your visit to Fnac.",
    human: "Of course. Tap “Call a staff member” and someone from the team will come to help you.",
    otherStore: "Books, comics, school books, CDs, vinyl records and DVDs are at Fnac Wilson, 16 allées Franklin-Roosevelt, near Jean-Jaurès. Here at Fnac Jeanne d'Arc, we specialise in technology.",
    otherStoreWhat: "Books, comics, school books, CDs, vinyl, DVDs",
    otherStoreNear: "Near Jean-Jaurès",
    otherStoreClose: "Back to the map",
    didYouMean: (word) => `Did you mean “${word}”? `,
    vendorConfirm: (zone) => zone
      ? `Done: a staff member from ${zone} has been notified.`
      : "Done: a staff member has been notified and is on their way.",
    vendorToast: (zone) => zone ? `Staff notified · ${zone}` : "Staff notified",
    micUnsupported: "The microphone isn't available on this device. You can type your question.",
    micError: "I didn't quite catch that. Try again, or type your question.",
    micDenied: "The microphone is blocked. Allow it in the browser, or type your question.",
    idleWarnTitle: "Are you still there?",
    idleWarnBody: (s) => `Back to the welcome screen in ${s} s.`,
    idleWarnButton: "I'm still here",
    floorName: (f) => FLOOR_NAMES.en[f]
  },
  es: {
    idleHello: "¡Hola!",
    idleTitle: "Soy Jeanne, su guía en la Fnac Jeanne d'Arc.",
    idleSub: "Dígame qué busca y le muestro dónde está.",
    idleBubble: "¡Bienvenido! ¿En qué puedo ayudarle?",
    idleCta: "Toque la pantalla para empezar",
    greeting: "¡Hola y bienvenido a la Fnac Jeanne d'Arc! Dígame qué busca y le muestro la sección en el plano.",
    switched: "Muy bien, seguimos en español. ¿Qué busca?",
    statusReady: "Hágame una pregunta",
    statusListening: "Le escucho…",
    statusSpeaking: "Jeanne le responde",
    micIdle: "Toque para hablar",
    micListening: "Le escucho… toque para parar",
    placeholder: "O escriba aquí: auriculares, PS5, iPhone…",
    send: "Enviar",
    suggestionsTitle: "Búsquedas frecuentes",
    vendor: "Llamar a un vendedor",
    accessibility: "Accesibilidad",
    end: "Terminar",
    mapTitle: "Plano de la tienda",
    floor0: "Planta 0",
    floorM1: "Sótano",
    youAreHere: "Usted está aquí",
    stepEntrance: "Entrada",
    stepStairs: "Escalera",
    routeHint: "Toque una sección del plano para ver qué hay.",
    found: (zone, floor) => floor === "-1"
      ? `La sección ${zone} está en el sótano. Baje por la escalera y siga el plano.`
      : `La sección ${zone} está aquí, en la planta 0. Se la indico en el plano.`,
    foundStairs: "Los LEGO, las figuras POP y las cartas Pokémon están en la escalera que une la planta 0 con el sótano.",
    foundEntrance: "La entrada y la salida están en la planta 0, abajo en el plano.",
    notFound: "No he encontrado ese producto. Pruebe con otra palabra, o llame a un vendedor: vendrá a ayudarle.",
    hello: "¡Hola! ¿Qué producto busca?",
    thanks: "¡Con mucho gusto! Disfrute de su visita a la Fnac.",
    human: "Por supuesto. Toque «Llamar a un vendedor» y alguien del equipo vendrá a ayudarle.",
    otherStore: "Los libros, cómics, libros de texto, CD, vinilos y DVD están en la Fnac Wilson, 16 allées Franklin-Roosevelt, cerca de Jean-Jaurès. Aquí, en la Fnac Jeanne d'Arc, estamos especializados en tecnología.",
    otherStoreWhat: "Libros, cómics, libros de texto, CD, vinilos, DVD",
    otherStoreNear: "Cerca de Jean-Jaurès",
    otherStoreClose: "Volver al plano",
    didYouMean: (word) => `¿Quiere decir «${word}»? `,
    vendorConfirm: (zone) => zone
      ? `Hecho: se ha avisado a un vendedor de la sección ${zone}.`
      : "Hecho: se ha avisado a un vendedor y ya viene.",
    vendorToast: (zone) => zone ? `Vendedor avisado · ${zone}` : "Vendedor avisado",
    micUnsupported: "El micrófono no está disponible en este dispositivo. Puede escribir su pregunta.",
    micError: "No le he entendido bien. Inténtelo de nuevo o escriba su pregunta.",
    micDenied: "El micrófono está bloqueado. Permítalo en el navegador o escriba su pregunta.",
    idleWarnTitle: "¿Sigue ahí?",
    idleWarnBody: (s) => `Volvemos a la pantalla de inicio en ${s} s.`,
    idleWarnButton: "Sigo aquí",
    floorName: (f) => FLOOR_NAMES.es[f]
  }
};

// =====================================================================
// Rayons du magasin.
// "floors" : étage(s) où le rayon apparaît sur le plan.
// "icon" : identifiant d'une icône de index.html (<symbol id="i-...">).
// "boost" : priorité quand plusieurs rayons correspondent.
// =====================================================================
export const ZONES = {
  // ---------------- Étage 0 ----------------
  telephonie: {
    floors: ["0"], icon: "smartphone",
    label: { fr: "Téléphonie Android", en: "Android phones", es: "Telefonía Android" },
    detail: { fr: "Écouteurs filaires, chargeurs…", en: "Wired earphones, chargers…", es: "Auriculares con cable, cargadores…" },
    keywords: {
      fr: ["téléphone", "téléphone portable", "portable", "mobile", "smartphone", "téléphone android", "android",
           "téléphone samsung", "samsung", "galaxy", "samsung galaxy", "galaxy s24", "galaxy s25", "galaxy a16",
           "galaxy a56", "galaxy z flip", "galaxy z fold", "xiaomi", "redmi", "poco", "google pixel", "pixel",
           "oppo", "honor", "motorola", "nokia", "oneplus", "realme", "wiko", "crosscall", "alcatel", "fairphone",
           "sony xperia", "xperia", "téléphone pas cher", "téléphone reconditionné", "smartphone reconditionné",
           "reconditionné", "téléphone senior", "téléphone à clapet", "téléphone fixe", "chargeur",
           "chargeur téléphone", "chargeur secteur", "chargeur rapide", "chargeur sans fil", "chargeur à induction",
           "chargeur voiture", "bloc secteur", "adaptateur secteur", "câble de charge", "câble usb c", "usb c",
           "câble micro usb", "micro usb", "batterie externe", "batterie de secours", "powerbank", "power bank",
           "écouteur filaire", "écouteurs filaires", "écouteurs jack", "kit mains libres", "oreillette",
           "oreillette bluetooth", "coque", "coque téléphone", "coque samsung", "coque xiaomi", "étui téléphone",
           "housse téléphone", "verre trempé", "protection écran", "protège écran", "film protecteur", "carte sim",
           "sim", "carte prépayée", "forfait", "forfait mobile", "abonnement mobile", "recharge téléphonique",
           "sfr", "orange", "bouygues", "free mobile", "support téléphone", "support voiture", "porte téléphone",
           "perche à selfie", "anneau téléphone", "popsocket", "reprise téléphone", "rachat téléphone",
           "téléphone enfant"],
      en: ["phone", "mobile phone", "mobile", "cell phone", "cellphone", "smartphone", "android", "android phone",
           "samsung", "samsung phone", "galaxy", "samsung galaxy", "galaxy s24", "galaxy s25", "galaxy z flip",
           "galaxy z fold", "xiaomi", "redmi", "poco", "google pixel", "pixel", "oppo", "honor", "motorola",
           "nokia", "oneplus", "realme", "fairphone", "sony xperia", "xperia", "cheap phone", "refurbished phone",
           "refurbished", "basic phone", "flip phone", "landline", "charger", "phone charger", "wall charger",
           "fast charger", "wireless charger", "car charger", "power adapter", "charging cable", "usb c cable",
           "usb c", "micro usb cable", "micro usb", "power bank", "portable battery", "battery pack",
           "wired earphone", "wired earphones", "jack earphones", "hands free kit", "earpiece",
           "bluetooth earpiece", "phone case", "case", "samsung case", "phone cover", "phone pouch",
           "tempered glass", "screen protector", "screen film", "sim card", "sim", "prepaid card", "mobile plan",
           "phone plan", "top up", "phone holder", "car mount", "selfie stick", "phone ring", "popsocket",
           "phone trade in", "kids phone"],
      es: ["teléfono", "teléfono móvil", "móvil", "celular", "smartphone", "android", "teléfono android", "samsung",
           "teléfono samsung", "galaxy", "samsung galaxy", "galaxy s24", "galaxy s25", "xiaomi", "redmi", "poco",
           "google pixel", "pixel", "oppo", "honor", "motorola", "nokia", "oneplus", "realme", "fairphone",
           "sony xperia", "xperia", "móvil barato", "móvil reacondicionado", "reacondicionado",
           "teléfono para mayores", "teléfono fijo", "cargador", "cargador de móvil", "cargador de red",
           "cargador rápido", "cargador inalámbrico", "cargador de coche", "adaptador de corriente",
           "cable de carga", "cable usb c", "usb c", "cable micro usb", "micro usb", "batería externa",
           "power bank", "powerbank", "auricular con cable", "auriculares con cable", "auriculares jack",
           "manos libres", "auricular bluetooth", "funda", "funda móvil", "funda samsung", "carcasa",
           "cristal templado", "protector de pantalla", "lámina protectora", "tarjeta sim", "sim",
           "tarjeta prepago", "tarifa móvil", "recarga", "soporte móvil", "soporte de coche", "palo selfie",
           "anillo para móvil", "popsocket", "móvil para niños"]
    }
  },
  objets: {
    floors: ["0"], icon: "watch",
    label: { fr: "Objets connectés", en: "Connected devices", es: "Objetos conectados" },
    detail: { fr: "Montres, maison connectée…", en: "Watches, smart home…", es: "Relojes, hogar conectado…" },
    keywords: {
      fr: ["objet connecté", "objets connectés", "montre connectée", "montres connectées", "montre", "smartwatch",
           "montre gps", "montre de sport", "montre cardio", "cardiofréquencemètre", "bracelet connecté",
           "bracelet d'activité", "tracker d'activité", "podomètre", "garmin", "fitbit", "montre polar", "suunto",
           "withings", "amazfit", "huawei watch", "galaxy watch", "samsung watch", "xiaomi band", "bague connectée",
           "balance connectée", "tensiomètre", "thermomètre connecté", "oxymètre", "maison connectée", "domotique",
           "ampoule connectée", "ampoule intelligente", "philips hue", "prise connectée", "prise intelligente",
           "interrupteur connecté", "thermostat", "thermostat connecté", "netatmo", "station météo",
           "caméra de surveillance", "caméra intérieure", "caméra extérieure", "caméra ip", "babyphone",
           "écoute bébé", "sonnette connectée", "sonnette vidéo", "ring", "nest", "google nest", "alarme",
           "alarme maison", "détecteur de fumée", "détecteur de mouvement", "serrure connectée", "verrou connecté",
           "assistant vocal", "alexa", "amazon echo", "echo dot", "google home", "enceinte connectée",
           "traceur gps", "tracker bluetooth", "porte-clés connecté", "robot tondeuse", "arrosage connecté",
           "volet connecté", "collier connecté", "gourde connectée", "reveil connecté"],
      en: ["connected device", "smart device", "smart watch", "smartwatch", "watch", "gps watch", "sports watch",
           "heart rate monitor", "fitness tracker", "activity tracker", "step counter", "garmin", "fitbit", "polar",
           "suunto", "withings", "amazfit", "huawei watch", "galaxy watch", "samsung watch", "xiaomi band",
           "smart ring", "smart scale", "blood pressure monitor", "smart thermometer", "smart home",
           "home automation", "smart bulb", "philips hue", "smart plug", "smart switch", "thermostat",
           "smart thermostat", "netatmo", "weather station", "security camera", "indoor camera", "outdoor camera",
           "ip camera", "baby monitor", "video doorbell", "doorbell", "ring", "nest", "google nest", "alarm",
           "home alarm", "smoke detector", "motion sensor", "smart lock", "voice assistant", "alexa", "amazon echo",
           "echo dot", "google home", "smart speaker", "gps tracker", "bluetooth tracker", "robot mower",
           "smart sprinkler", "smart blinds"],
      es: ["objeto conectado", "dispositivo inteligente", "reloj conectado", "reloj inteligente", "reloj",
           "smartwatch", "reloj gps", "reloj deportivo", "pulsómetro", "pulsera de actividad", "podómetro",
           "garmin", "fitbit", "reloj polar", "suunto", "withings", "amazfit", "huawei watch", "galaxy watch",
           "samsung watch", "xiaomi band", "anillo inteligente", "báscula conectada", "tensiómetro",
           "termómetro conectado", "hogar conectado", "domótica", "bombilla inteligente", "philips hue",
           "enchufe inteligente", "interruptor inteligente", "termostato", "termostato inteligente", "netatmo",
           "estación meteorológica", "cámara de vigilancia", "cámara interior", "cámara exterior", "cámara ip",
           "vigilabebés", "timbre inteligente", "timbre con cámara", "ring", "nest", "google nest", "alarma",
           "alarma para casa", "detector de humo", "detector de movimiento", "cerradura inteligente",
           "asistente de voz", "alexa", "amazon echo", "echo dot", "google home", "altavoz inteligente",
           "localizador gps", "rastreador bluetooth", "robot cortacésped"]
    }
  },
  escalier: {
    floors: ["0", "-1"], icon: "stairs",
    label: { fr: "Escalier · LEGO, POP & Pokémon", en: "Stairs · LEGO, POP & Pokémon", es: "Escalera · LEGO, POP y Pokémon" },
    detail: { fr: "", en: "", es: "" },
    keywords: {
      fr: ["lego", "lego technic", "lego star wars", "lego city", "lego friends", "lego harry potter", "lego icons",
           "briques lego", "jeu de construction", "figurine", "figurines", "figurine pop", "figurines pop", "funko",
           "funko pop", "bobblehead", "goodies", "figurine manga", "figurine anime", "objet de collection",
           "pokemon", "carte pokemon", "cartes pokemon", "booster", "booster pokemon", "display pokemon",
           "coffret pokemon", "elite trainer box", "carte à collectionner", "cartes à collectionner",
           "cartes magic", "magic the gathering", "yu-gi-oh", "one piece card game", "classeur à cartes",
           "protège cartes", "escalier", "escaliers", "sous-sol", "descendre", "en bas", "étage du dessous"],
      en: ["lego", "lego technic", "lego star wars", "lego city", "lego friends", "lego harry potter", "lego icons",
           "lego bricks", "building set", "figure", "figurine", "pop figure", "pop figures", "funko", "funko pop",
           "bobblehead", "collectible", "collectibles", "anime figure", "manga figure", "pokemon", "pokemon card",
           "pokemon cards", "booster", "pokemon booster", "pokemon box", "elite trainer box", "trading card",
           "trading cards", "magic cards", "magic the gathering", "yu-gi-oh", "one piece card game", "card binder",
           "card sleeves", "stairs", "staircase", "downstairs", "basement", "lower floor"],
      es: ["lego", "lego technic", "lego star wars", "lego city", "lego friends", "lego harry potter", "lego icons",
           "piezas lego", "juego de construcción", "figura", "figuras", "figura pop", "figuras pop", "funko",
           "funko pop", "cabezón", "artículo de colección", "figura manga", "figura anime", "pokemon",
           "carta pokemon", "cartas pokemon", "sobre", "sobre pokemon", "caja pokemon", "elite trainer box",
           "carta coleccionable", "cartas coleccionables", "cartas magic", "magic the gathering", "yu-gi-oh",
           "one piece card game", "archivador de cartas", "fundas para cartas", "escalera", "escaleras", "sótano",
           "abajo", "planta de abajo"]
    }
  },
  entree: {
    floors: ["0"], icon: "door",
    label: { fr: "Entrée / Sortie", en: "Entrance / Exit", es: "Entrada / Salida" },
    detail: { fr: "", en: "", es: "" },
    keywords: {
      fr: ["entrée", "sortie", "porte", "porte d'entrée", "sortie de secours", "je veux sortir", "où sortir",
           "comment sortir", "par où entrer"],
      en: ["entrance", "exit", "way out", "door", "front door", "emergency exit", "how to get out", "where to exit"],
      es: ["entrada", "salida", "puerta", "puerta de entrada", "salida de emergencia", "cómo salir",
           "por dónde salir"]
    }
  },

  // ---------------- Niveau -1 ----------------
  gaming: {
    floors: ["-1"], icon: "gamepad",
    label: { fr: "Jeux vidéo", en: "Video games", es: "Videojuegos" },
    detail: { fr: "Consoles et jeux", en: "Consoles and games", es: "Consolas y juegos" },
    keywords: {
      fr: ["jeu vidéo", "jeux vidéo", "console", "consoles", "console de jeux", "console de salon",
           "console portable", "playstation", "playstation 5", "ps5", "ps5 pro", "ps4", "ps3", "xbox",
           "xbox series x", "xbox series s", "xbox series", "xbox one", "nintendo", "nintendo switch", "switch",
           "switch 2", "switch oled", "switch lite", "steam deck", "manette", "manettes", "manette ps5",
           "manette xbox", "manette switch", "manette pro", "joy-con", "dualsense", "dualshock", "jeu ps5",
           "jeu ps4", "jeu xbox", "jeu switch", "jeu nintendo", "jeu pc", "jeu pokemon", "jeu d'occasion",
           "jeu de course", "jeu de foot", "jeu de tir", "jeu vidéo enfant", "precommande jeu", "carte psn", "carte xbox",
           "carte nintendo", "carte cadeau jeu", "abonnement game pass", "game pass", "playstation plus", "ps plus",
           "nintendo switch online", "fifa", "ea sports fc", "call of duty", "cod", "gta", "gta 6", "zelda",
           "mario", "mario kart", "pokemon jeu", "minecraft", "fortnite", "les sims", "assassin's creed",
           "elden ring", "wolverine", "spider-man", "hogwarts legacy", "f1", "nba 2k", "just dance", "casque vr",
           "réalité virtuelle", "meta quest", "psvr", "volant de course", "volant gaming",
           "station de charge manette", "housse switch", "carte mémoire switch", "stockage console",
           "kit nettoyage console"],
      en: ["video game", "video games", "game", "console", "consoles", "games console", "handheld console",
           "playstation", "playstation 5", "ps5", "ps5 pro", "ps4", "ps3", "xbox", "xbox series x", "xbox series s",
           "xbox one", "nintendo", "nintendo switch", "switch", "switch 2", "switch oled", "switch lite",
           "steam deck", "controller", "controllers", "ps5 controller", "xbox controller", "switch controller",
           "pro controller", "joy-con", "dualsense", "ps5 game", "xbox game", "switch game", "pc game",
           "pokemon game", "used game", "second hand game", "racing game", "football game", "kids video game", "psn card",
           "xbox card", "nintendo card", "game gift card", "game pass", "playstation plus",
           "nintendo switch online", "fifa", "ea sports fc", "call of duty", "gta", "zelda", "mario", "mario kart",
           "minecraft", "fortnite", "the sims", "assassins creed", "elden ring", "wolverine", "spider-man",
           "hogwarts legacy", "vr headset", "virtual reality", "meta quest", "psvr", "racing wheel",
           "charging dock", "switch case", "switch memory card"],
      es: ["videojuego", "videojuegos", "consola", "consolas", "consola portátil", "playstation", "playstation 5",
           "ps5", "ps5 pro", "ps4", "ps3", "xbox", "xbox series x", "xbox series s", "xbox one", "nintendo",
           "nintendo switch", "switch", "switch 2", "switch oled", "switch lite", "steam deck", "mando", "mandos",
           "mando ps5", "mando xbox", "mando switch", "mando pro", "joy-con", "dualsense", "juego ps5",
           "juego xbox", "juego switch", "juego pc", "juego pokemon", "juego de segunda mano", "juego de carreras",
           "juego de fútbol", "juego para niños", "tarjeta psn", "tarjeta xbox", "tarjeta nintendo", "game pass",
           "playstation plus", "nintendo switch online", "fifa", "ea sports fc", "call of duty", "gta", "zelda",
           "mario", "mario kart", "minecraft", "fortnite", "los sims", "assassins creed", "elden ring", "wolverine",
           "spider-man", "gafas vr", "realidad virtual", "meta quest", "psvr", "volante de carreras",
           "base de carga", "funda switch", "tarjeta de memoria switch"]
    }
  },
  accessoiresGaming: {
    floors: ["-1"], icon: "mouse",
    label: { fr: "Accessoires gaming & cartouches", en: "Gaming gear & ink", es: "Accesorios gaming y cartuchos" },
    detail: { fr: "PC gamer, écrans gamer, souris, claviers, encre", en: "Gaming PCs, monitors, mice, keyboards, ink", es: "PC gaming, monitores, ratones, teclados, tinta" },
    keywords: {
      fr: ["accessoire gaming", "accessoires gaming", "matériel gaming", "setup gaming", "souris", "souris gaming",
           "souris gamer", "souris sans fil", "clavier", "clavier gaming", "clavier gamer", "clavier mécanique",
           "clavier sans fil", "casque gamer", "casque gaming", "micro-casque", "tapis de souris",
           "tapis de souris xxl", "siège gamer", "fauteuil gamer", "chaise gaming", "bureau gamer", "pc gamer",
           "pc gaming", "tour gamer", "unité centrale gamer", "écran gamer", "écran gaming", "écran 144 hz",
           "écran 240 hz", "carte graphique", "rtx", "geforce", "nvidia", "amd", "radeon", "carte mère",
           "processeur", "ram", "mémoire vive", "barrette de ram", "ventirad", "watercooling", "refroidissement pc",
           "boîtier pc", "alimentation pc", "ventilateur pc", "montage pc", "razer", "logitech", "steelseries",
           "corsair", "hyperx", "asus rog", "roccat", "turtle beach", "elgato", "stream deck", "carte de capture",
           "micro streaming", "ruban led", "led gaming", "hub usb gaming", "volant pc", "cartouche", "cartouches",
           "cartouche d'encre", "cartouches d'encre", "encre", "encre imprimante", "cartouche hp",
           "cartouche canon", "cartouche epson", "cartouche brother", "toner", "tambour imprimante",
           "kit de recharge encre"],
      en: ["gaming gear", "gaming accessory", "gaming accessories", "gaming setup", "mouse", "mice", "gaming mouse",
           "wireless mouse", "keyboard", "gaming keyboard", "mechanical keyboard", "wireless keyboard",
           "gaming headset", "headset", "mouse pad", "desk mat", "gaming chair", "gaming desk", "gaming pc",
           "gaming laptop", "gaming tower", "gaming monitor", "144 hz monitor", "240 hz monitor", "graphics card",
           "gpu", "rtx", "geforce", "nvidia", "amd", "radeon", "motherboard", "processor", "cpu", "ram",
           "memory stick", "cooler", "water cooling", "pc case", "power supply", "pc fan", "razer", "logitech",
           "steelseries", "corsair", "hyperx", "asus rog", "roccat", "turtle beach", "elgato", "stream deck",
           "capture card", "streaming mic", "led strip", "gaming led", "racing wheel pc", "ink", "ink cartridge",
           "ink cartridges", "cartridge", "cartridges", "hp cartridge", "canon cartridge", "epson cartridge",
           "brother cartridge", "toner", "printer drum"],
      es: ["accesorio gaming", "accesorios gaming", "equipo gaming", "setup gaming", "ratón", "ratón gaming",
           "ratón inalámbrico", "teclado", "teclado gaming", "teclado mecánico", "teclado inalámbrico",
           "auriculares gaming", "cascos gaming", "alfombrilla", "alfombrilla xxl", "silla gaming",
           "escritorio gaming", "pc gaming", "portátil gaming", "torre gaming", "monitor gaming", "monitor 144 hz",
           "tarjeta gráfica", "rtx", "geforce", "nvidia", "amd", "radeon", "placa base", "procesador", "ram",
           "memoria ram", "refrigeración líquida", "ventilador pc", "caja pc", "fuente de alimentación", "razer",
           "logitech", "steelseries", "corsair", "hyperx", "asus rog", "roccat", "turtle beach", "elgato",
           "stream deck", "capturadora", "micrófono streaming", "tira led", "volante pc", "cartucho", "cartuchos",
           "cartucho de tinta", "cartuchos de tinta", "tinta", "tinta impresora", "cartucho hp", "cartucho canon",
           "cartucho epson", "cartucho brother", "tóner", "tambor de impresora"]
    }
  },
  electromenager: {
    floors: ["-1"], icon: "plug",
    label: { fr: "Petit électroménager", en: "Home appliances", es: "Pequeños electrodomésticos" },
    detail: { fr: "Aspirateurs, cuisine, soin, Dyson…", en: "Vacuums, kitchen, personal care, Dyson…", es: "Aspiradoras, cocina, cuidado personal, Dyson…" },
    keywords: {
      fr: ["électroménager", "petit électroménager", "aspirateur", "aspirateurs", "aspirateur balai",
           "aspirateur robot", "aspirateur sans fil", "aspirateur traîneau", "aspirateur à main",
           "robot aspirateur", "dyson", "rowenta", "roomba", "irobot", "nettoyeur vapeur", "balai vapeur",
           "karcher", "nettoyeur haute pression", "sèche-cheveux", "lisseur", "lisseur à cheveux", "boucleur",
           "fer à boucler", "brosse soufflante", "airwrap", "babyliss", "remington", "rasoir", "rasoir électrique",
           "tondeuse", "tondeuse à barbe", "tondeuse à cheveux", "épilateur", "lumière pulsée", "braun",
           "brosse à dents électrique", "oral b", "hydropulseur", "machine à café", "cafetière", "cafetière filtre",
           "machine expresso", "expresso", "nespresso", "senseo", "dolce gusto", "tassimo", "delonghi", "krups",
           "magimix", "moulin à café", "broyeur à café", "bouilloire", "théière électrique", "airfryer",
           "air fryer", "friteuse", "friteuse sans huile", "ninja", "cookeo", "companion", "robot cuiseur",
           "robot pâtissier", "robot de cuisine", "kitchenaid", "blender", "mixeur", "mixeur plongeant", "hachoir",
           "centrifugeuse", "extracteur de jus", "presse-agrumes", "micro-ondes", "mini four", "four posable",
           "grille-pain", "toaster", "gaufrier", "crêpière", "appareil à raclette", "pierrade",
           "plancha électrique", "machine à pain", "yaourtière", "sorbetière", "machine sous vide", "sodastream",
           "machine à soda", "fer à repasser", "centrale vapeur", "défroisseur", "pèse-personne",
           "balance connectée cuisine", "balance de cuisine", "ventilateur", "brumisateur", "chauffage d'appoint",
           "radiateur", "climatiseur", "climatiseur mobile", "déshumidificateur", "purificateur d'air",
           "humidificateur", "diffuseur d'huiles essentielles", "barbecue électrique", "cave à vin", "réfrigérateur",
              "capsule", "capsules", "dosette", "dosettes", "machine à capsules", "café en grains", "café moulu", "détartrant"],
      en: ["home appliance", "appliances", "small appliance", "vacuum", "vacuum cleaner", "cordless vacuum",
           "stick vacuum", "robot vacuum", "handheld vacuum", "dyson", "rowenta", "roomba", "irobot",
           "steam cleaner", "steam mop", "karcher", "pressure washer", "hair dryer", "hair straightener",
           "straightener", "curler", "curling iron", "hot air brush", "airwrap", "babyliss", "remington", "shaver",
           "electric shaver", "trimmer", "beard trimmer", "hair clipper", "epilator", "ipl", "braun",
           "electric toothbrush", "oral b", "water flosser", "coffee machine", "coffee maker", "filter coffee",
           "espresso machine", "espresso", "nespresso", "senseo", "dolce gusto", "tassimo", "delonghi", "krups",
           "coffee grinder", "bean to cup", "kettle", "electric kettle", "air fryer", "deep fryer", "fryer",
           "ninja", "multicooker", "food processor", "stand mixer", "kitchenaid", "blender", "hand blender",
           "chopper", "juicer", "citrus press", "microwave", "mini oven", "toaster", "waffle maker", "crepe maker",
           "raclette", "electric grill", "bread maker", "yogurt maker", "ice cream maker", "vacuum sealer",
           "sodastream", "soda maker", "iron", "steam generator", "garment steamer", "bathroom scale",
           "kitchen scale", "fan", "heater", "air conditioner", "portable air conditioner", "dehumidifier",
           "air purifier", "humidifier", "diffuser", "wine cooler", "fridge",
              "coffee capsule", "capsules", "pods", "coffee pods", "capsule machine", "coffee beans", "descaler"],
      es: ["electrodoméstico", "electrodomésticos", "pequeño electrodoméstico", "aspiradora", "aspirador",
           "aspirador escoba", "aspirador sin cable", "robot aspirador", "aspirador de mano", "dyson", "rowenta",
           "roomba", "irobot", "limpiador de vapor", "mopa de vapor", "karcher", "hidrolimpiadora", "secador",
           "secador de pelo", "plancha de pelo", "alisador", "rizador", "cepillo de aire", "airwrap", "babyliss",
           "remington", "afeitadora", "afeitadora eléctrica", "cortapelos", "recortadora de barba", "depiladora",
           "luz pulsada", "braun", "cepillo de dientes eléctrico", "oral b", "irrigador dental", "cafetera",
           "cafetera de goteo", "cafetera espresso", "espresso", "nespresso", "senseo", "dolce gusto", "tassimo",
           "delonghi", "krups", "molinillo de café", "cafetera superautomática", "hervidor", "freidora de aire",
           "freidora", "ninja", "robot de cocina", "amasadora", "kitchenaid", "batidora", "batidora de mano",
           "picadora", "licuadora", "exprimidor", "microondas", "mini horno", "tostadora", "gofrera", "crepera",
           "raclette", "plancha de cocina", "panificadora", "yogurtera", "heladera", "envasadora al vacío",
           "sodastream", "plancha", "plancha de ropa", "centro de planchado", "vaporizador de ropa", "báscula",
           "báscula de cocina", "ventilador", "calefactor", "aire acondicionado", "deshumidificador",
           "purificador de aire", "humidificador", "difusor", "vinoteca", "nevera",
              "cápsula", "cápsulas", "monodosis", "cafetera de cápsulas", "café en grano", "descalcificador"]
    }
  },
  pcwindows: {
    floors: ["-1"], icon: "laptop",
    label: { fr: "PC Windows & accessoires", en: "Windows PCs & accessories", es: "PC Windows y accesorios" },
    detail: { fr: "Tablettes, écrans, imprimantes, câbles, stockage", en: "Tablets, monitors, printers, cables, storage", es: "Tabletas, monitores, impresoras, cables, almacenamiento" },
    keywords: {
      fr: ["pc", "pc windows", "pc portable", "ordinateur", "ordinateur portable", "ordi", "portable windows",
           "pc fixe", "unité centrale", "tour pc", "tout-en-un", "laptop", "notebook", "ultrabook", "chromebook",
           "asus", "hp", "lenovo", "acer", "dell", "msi", "huawei matebook", "microsoft surface", "surface pro",
           "windows", "windows 11", "pack office", "microsoft 365", "logiciel", "antivirus", "suite bureautique",
           "tablette", "tablettes", "tablette android", "tablette samsung", "galaxy tab", "tablette enfant",
           "liseuse", "kobo", "écran", "écran pc", "écran d'ordinateur", "moniteur", "écran 24 pouces",
           "écran 27 pouces", "double écran", "imprimante", "imprimante jet d'encre", "imprimante laser",
           "imprimante multifonction", "multifonction", "imprimante wifi", "scanner", "photocopie", "papier",
           "ramette de papier", "clé usb", "disque dur", "disque dur externe", "ssd", "ssd externe", "nvme",
           "stockage", "carte micro sd", "lecteur de carte", "graveur", "lecteur dvd externe", "câble",
           "câble hdmi", "hdmi", "displayport", "vga", "câble vga", "rj45", "ethernet", "câble ethernet",
           "câble usb", "rallonge usb", "hub usb", "station d'accueil", "dock usb c", "adaptateur",
           "adaptateur hdmi", "adaptateur usb c", "multiprise", "rallonge électrique", "parasurtenseur", "onduleur",
           "répéteur wifi", "routeur", "box wifi", "cpl", "clé wifi", "antenne wifi", "sacoche ordinateur",
           "housse ordinateur", "sac à dos pc", "support ordinateur", "refroidisseur pc", "chargeur ordinateur",
           "chargeur pc portable", "batterie pc portable", "nettoyant écran", "bombe à air sec"],
      en: ["pc", "windows pc", "laptop", "computer", "desktop computer", "desktop pc", "tower pc", "all in one",
           "notebook", "ultrabook", "chromebook", "asus", "hp", "lenovo", "acer", "dell", "msi", "huawei matebook",
           "microsoft surface", "surface pro", "windows", "windows 11", "office suite", "microsoft 365", "software",
           "antivirus", "tablet", "tablets", "android tablet", "samsung tablet", "galaxy tab", "kids tablet",
           "e-reader", "kobo", "screen", "monitor", "pc monitor", "computer screen", "24 inch monitor",
           "27 inch monitor", "dual screen", "printer", "inkjet printer", "laser printer", "all in one printer",
           "wifi printer", "scanner", "paper", "printer paper", "usb stick", "usb key", "flash drive", "hard drive",
           "hard disk", "external drive", "ssd", "external ssd", "nvme", "storage", "micro sd card", "card reader",
           "external dvd drive", "cable", "hdmi", "hdmi cable", "displayport", "vga", "vga cable", "rj45",
           "ethernet", "ethernet cable", "usb cable", "usb extension", "usb hub", "docking station", "usb c dock",
           "adapter", "hdmi adapter", "usb c adapter", "power strip", "extension cord", "surge protector", "ups",
           "wifi extender", "router", "wifi box", "powerline", "wifi dongle", "laptop bag", "laptop sleeve",
           "laptop backpack", "laptop stand", "cooling pad", "laptop charger", "laptop battery", "screen cleaner",
           "compressed air"],
      es: ["pc", "pc windows", "portátil", "ordenador", "ordenador portátil", "ordenador de sobremesa", "torre",
           "todo en uno", "notebook", "ultrabook", "chromebook", "asus", "hp", "lenovo", "acer", "dell", "msi",
           "huawei matebook", "microsoft surface", "surface pro", "windows", "windows 11", "microsoft office",
           "microsoft 365", "software", "antivirus", "tableta", "tablet", "tableta android", "tableta samsung",
           "galaxy tab", "tablet para niños", "lector de libros", "kobo", "pantalla", "monitor", "monitor pc",
           "pantalla de ordenador", "monitor 24 pulgadas", "monitor 27 pulgadas", "impresora", "impresora de tinta",
           "impresora láser", "impresora multifunción", "multifunción", "impresora wifi", "escáner", "papel",
           "papel de impresora", "memoria usb", "pendrive", "disco duro", "disco duro externo", "ssd",
           "ssd externo", "nvme", "almacenamiento", "tarjeta micro sd", "lector de tarjetas", "lector dvd externo",
           "cable", "cable hdmi", "hdmi", "displayport", "vga", "cable vga", "rj45", "ethernet", "cable ethernet",
           "cable usb", "alargador usb", "hub usb", "estación de acoplamiento", "dock usb c", "adaptador",
           "adaptador hdmi", "adaptador usb c", "regleta", "alargador", "protector de sobretensión", "sai",
           "repetidor wifi", "router", "powerline", "adaptador wifi", "funda portátil", "mochila portátil",
           "soporte portátil", "base refrigeradora", "cargador portátil", "batería portátil",
           "limpiador de pantallas", "aire comprimido"]
    }
  },
  trottinettes: {
    floors: ["-1"], icon: "scooter",
    label: { fr: "Mobilité urbaine", en: "Urban mobility", es: "Movilidad urbana" },
    detail: { fr: "Trottinettes, casques, figurines POP", en: "Scooters, helmets, POP figures", es: "Patinetes, cascos, figuras POP" },
    keywords: {
      fr: ["trottinette", "trottinettes", "trotinette", "trottinette électrique", "trottinette enfant", "ninebot",
           "segway", "xiaomi trottinette", "hoverboard", "gyroroue", "monoroue", "skateboard électrique",
           "vélo électrique", "vélo pliant", "casque trottinette", "casque de trottinette", "casque vélo",
           "protections", "genouillères", "coudières", "antivol", "cadenas vélo", "gonfleur", "pompe à vélo",
           "batterie trottinette", "chargeur trottinette", "mobilité urbaine", "mobilité douce",
           "engin de déplacement", "pièces trottinette", "pneu trottinette"],
      en: ["scooter", "scooters", "electric scooter", "kids scooter", "ninebot", "segway", "xiaomi scooter",
           "hoverboard", "unicycle", "electric unicycle", "electric skateboard", "electric bike", "e-bike",
           "folding bike", "scooter helmet", "bike helmet", "helmet", "knee pads", "elbow pads", "bike lock",
           "lock", "pump", "scooter battery", "scooter charger", "urban mobility", "scooter parts", "scooter tyre"],
      es: ["patinete", "patinetes", "patinete eléctrico", "patinete infantil", "ninebot", "segway",
           "patinete xiaomi", "hoverboard", "monociclo eléctrico", "monopatín eléctrico", "bicicleta eléctrica",
           "bicicleta plegable", "casco patinete", "casco de patinete", "casco de bici", "rodilleras", "coderas",
           "candado", "candado de bici", "bomba de aire", "batería patinete", "cargador patinete",
           "movilidad urbana", "piezas patinete", "rueda patinete"]
    }
  },
  photo: {
    floors: ["-1"], icon: "camera",
    label: { fr: "Photo & micros", en: "Photo & microphones", es: "Foto y micrófonos" },
    detail: { fr: "Appareils, drones, micros-cravates", en: "Cameras, drones, lapel mics", es: "Cámaras, drones, micrófonos de corbata" },
    keywords: {
      fr: ["photo", "appareil photo", "appareils photo", "appareil photo numérique", "appareil photo jetable",
           "appareil jetable", "reflex", "hybride", "compact", "bridge", "appareil instantané", "polaroid",
           "instax", "fujifilm", "canon", "nikon", "sony alpha", "lumix", "panasonic lumix", "olympus", "pentax",
           "caméra", "caméra sport", "caméra embarquée", "gopro", "insta360", "dji", "drone", "drones", "osmo",
           "stabilisateur", "gimbal", "trépied", "monopode", "perche photo", "objectif", "objectifs",
           "téléobjectif", "grand angle", "zoom photo", "filtre photo", "flash", "flash cobra", "éclairage studio",
           "boîte à lumière", "fond vert", "sacoche photo", "sac photo", "carte sd", "carte cf",
           "batterie appareil photo", "chargeur batterie photo", "imprimante photo", "tirage photo", "album photo",
           "cadre photo numérique", "scanner de diapositives", "jumelles", "micro", "microphone", "micro cravate",
           "micro podcast", "micro studio", "micro usb-c", "perche micro", "rode", "enregistreur audio",
           "bonnette anti-vent", "mixette",
              "filmer", "faire des vidéos", "prendre des photos", "photographier", "vlog", "youtubeur", "tourner une vidéo", "filmer mes vacances", "matériel vidéo", "matériel photo", "studio photo", "podcast"],
      en: ["photo", "camera", "cameras", "digital camera", "disposable camera", "dslr", "mirrorless",
           "compact camera", "bridge camera", "instant camera", "polaroid", "instax", "fujifilm", "canon", "nikon",
           "sony alpha", "lumix", "olympus", "pentax", "action camera", "gopro", "insta360", "dji", "drone",
           "drones", "osmo", "stabilizer", "gimbal", "tripod", "monopod", "lens", "lenses", "telephoto",
           "wide angle", "photo filter", "flash", "studio light", "softbox", "green screen", "camera bag",
           "sd card", "cf card", "camera battery", "battery charger", "photo printer", "photo print",
           "digital photo frame", "binoculars", "mic", "microphone", "lapel mic", "podcast mic", "studio mic",
           "boom pole", "rode", "audio recorder", "windscreen",
              "filming", "make videos", "take photos", "vlogging", "youtuber", "shoot video", "video gear", "photo gear", "podcast"],
      es: ["foto", "cámara", "cámaras", "cámara de fotos", "cámara digital", "cámara desechable", "réflex",
           "sin espejo", "cámara compacta", "cámara instantánea", "polaroid", "instax", "fujifilm", "canon",
           "nikon", "sony alpha", "lumix", "olympus", "pentax", "cámara deportiva", "gopro", "insta360", "dji",
           "dron", "drones", "osmo", "estabilizador", "gimbal", "trípode", "monopié", "objetivo", "objetivos",
           "teleobjetivo", "gran angular", "filtro fotográfico", "flash", "luz de estudio", "ventana de luz",
           "croma", "bolsa para cámara", "tarjeta sd", "tarjeta cf", "batería de cámara", "cargador de batería",
           "impresora fotográfica", "revelado de fotos", "marco digital", "prismáticos", "micro", "micrófono",
           "micrófono de corbata", "micrófono de podcast", "micrófono de estudio", "rode", "grabadora de audio",
              "grabar vídeo", "hacer vídeos", "hacer fotos", "vlog", "youtuber", "equipo de vídeo", "equipo de foto", "podcast"]
    }
  },
  tv: {
    floors: ["-1"], icon: "tv",
    label: { fr: "TV", en: "TV", es: "TV" },
    detail: { fr: "Téléviseurs", en: "Televisions", es: "Televisores" },
    keywords: {
      fr: ["tv", "télé", "télévision", "téléviseur", "téléviseurs", "smart tv", "tv connectée", "oled", "qled",
           "mini led", "tv 4k", "tv 8k", "55 pouces", "65 pouces", "75 pouces", "petite télé", "tv samsung",
           "tv lg", "tv philips", "tv tcl", "hisense", "sony bravia", "télécommande", "télécommande universelle",
           "support tv", "support mural tv", "pied de tv", "meuble tv", "vidéoprojecteur", "projecteur",
           "écran de projection", "box android tv", "chromecast", "fire tv stick", "décodeur tnt",
           "antenne tv", "câble antenne", "installation tv", "livraison tv", "reprise ancienne tv", "lunettes 3d"],
      en: ["tv", "television", "telly", "smart tv", "oled", "qled", "mini led", "4k tv", "8k tv", "55 inch",
           "65 inch", "75 inch", "small tv", "samsung tv", "lg tv", "philips tv", "tcl tv", "hisense",
           "sony bravia", "remote", "remote control", "universal remote", "tv mount", "wall mount", "tv stand",
           "tv unit", "projector", "video projector", "projection screen", "android tv box", "chromecast",
           "fire tv stick", "tv aerial", "antenna cable", "tv delivery", "tv installation"],
      es: ["tv", "tele", "televisor", "televisores", "televisión", "smart tv", "oled", "qled", "mini led", "tv 4k",
           "tv 8k", "55 pulgadas", "65 pulgadas", "75 pulgadas", "tele pequeña", "tv samsung", "tv lg",
           "tv philips", "tv tcl", "hisense", "sony bravia", "mando a distancia", "mando universal",
           "soporte tv", "soporte de pared", "mueble tv", "proyector", "videoproyector", "pantalla de proyección",
           "android tv box", "chromecast", "fire tv stick", "antena tv", "cable de antena",
           "instalación tv"]
    }
  },
  audio: {
    floors: ["-1"], icon: "headphones",
    label: { fr: "Audio", en: "Audio", es: "Audio" },
    detail: { fr: "Casques, enceintes, platines", en: "Headphones, speakers, turntables", es: "Auriculares, altavoces, tocadiscos" },
    keywords: {
      fr: ["audio", "casque", "casques", "casque audio", "casque bluetooth", "casque sans fil",
           "casque à réduction de bruit", "réduction de bruit", "casque filaire", "casque studio", "casque enfant",
           "écouteurs", "écouteurs sans fil", "écouteurs bluetooth", "true wireless", "intra-auriculaire",
           "oreillettes sans fil", "bose", "sony wh", "sennheiser", "beats", "marshall", "bang olufsen",
           "harman kardon", "skullcandy", "anker soundcore", "jbl", "sonos", "devialet", "cabasse", "focal",
           "enceinte", "enceintes", "enceinte bluetooth", "enceinte portable", "enceinte waterproof",
           "mini enceinte", "grosse enceinte", "caisson de basses", "barre de son", "home cinéma", "ampli",
           "amplificateur", "chaîne hifi", "hifi", "platine", "platine vinyle", "tourne-disque", "lecteur cd",
           "lecteur mp3", "baladeur", "dictaphone", "radio", "radio réveil", "poste de radio", "dab", "réveil",
           "adaptateur bluetooth", "récepteur bluetooth", "câble jack", "adaptateur jack", "câble audio",
           "câble optique", "rallonge casque", "embouts casque", "coussinets casque", "support casque", "karaoké",
           "micro karaoké", "table de mixage", "instrument"],
      en: ["audio", "headphone", "headphones", "wireless headphones", "bluetooth headphones", "noise cancelling",
           "noise cancelling headphones", "wired headphones", "studio headphones", "kids headphones", "earphone",
           "earphones", "earbuds", "wireless earbuds", "true wireless", "in ear", "bose", "sony wh", "sennheiser",
           "beats", "marshall", "bang olufsen", "harman kardon", "skullcandy", "anker soundcore", "jbl", "sonos",
           "devialet", "focal", "speaker", "speakers", "bluetooth speaker", "portable speaker",
           "waterproof speaker", "subwoofer", "soundbar", "home cinema", "amplifier", "hifi", "hi-fi system",
           "turntable", "record player", "cd player", "mp3 player", "walkman", "voice recorder", "radio",
           "clock radio", "dab radio", "alarm clock", "bluetooth adapter", "bluetooth receiver", "jack cable",
           "jack adapter", "audio cable", "optical cable", "ear tips", "ear pads", "headphone stand", "karaoke",
           "karaoke mic", "mixer"],
      es: ["audio", "auricular", "auriculares", "cascos", "auriculares inalámbricos", "auriculares bluetooth",
           "cancelación de ruido", "auriculares con cancelación de ruido", "auriculares de estudio",
           "auriculares para niños", "auriculares de botón", "true wireless", "bose", "sony wh", "sennheiser",
           "beats", "marshall", "bang olufsen", "harman kardon", "skullcandy", "anker soundcore", "jbl", "sonos",
           "devialet", "focal", "altavoz", "altavoces", "altavoz bluetooth", "altavoz portátil",
           "altavoz resistente al agua", "subwoofer", "barra de sonido", "home cinema", "amplificador",
           "cadena hifi", "hifi", "tocadiscos", "giradiscos", "reproductor de cd", "reproductor mp3",
           "grabadora de voz", "radio", "radio despertador", "dab", "despertador", "adaptador bluetooth",
           "receptor bluetooth", "cable jack", "adaptador jack", "cable de audio", "cable óptico", "almohadillas",
           "soporte para auriculares", "karaoke", "micrófono de karaoke", "mesa de mezclas"]
    }
  },
  apple: {
    floors: ["-1"], icon: "apple",
    // Priorité : tout ce qui cite un produit Apple va au rayon Apple.
    boost: 20,
    label: { fr: "Apple", en: "Apple", es: "Apple" },
    detail: { fr: "iPhone, iPad, Mac, accessoires", en: "iPhone, iPad, Mac, accessories", es: "iPhone, iPad, Mac, accesorios" },
    keywords: {
      fr: ["apple", "apple store", "iphone", "iphone 15", "iphone 16", "iphone 17", "iphone 18", "iphone pro",
              "iphone pro max", "iphone plus", "iphone reconditionné", "ipad", "ipad air", "ipad pro", "ipad mini",
              "ipod", "airpods", "airpods pro", "airpods max", "mac", "macbook", "macbook air", "macbook pro",
              "imac", "mac mini", "mac studio", "apple watch", "apple watch ultra", "apple watch se",
              "montre apple", "apple pencil", "magic keyboard", "magic mouse", "magsafe", "lightning", "airtag",
              "apple tv", "homepod", "coque iphone", "étui iphone", "housse ipad", "coque ipad",
              "verre trempé iphone", "protection iphone", "chargeur iphone", "chargeur apple", "câble lightning",
              "câble apple", "adaptateur apple", "clavier ipad", "tablette apple", "ordinateur apple",
              "écouteurs apple", "carte cadeau apple", "applecare", "icloud", "app store", "itunes",
              "airpods de remplacement", "embouts airpods", "bracelet apple watch", "support iphone", "dock apple"],
      en: ["apple", "apple store", "iphone", "iphone 15", "iphone 16", "iphone 17", "iphone 18", "iphone pro",
              "iphone pro max", "refurbished iphone", "ipad", "ipad air", "ipad pro", "ipad mini", "ipod",
              "airpods", "airpods pro", "airpods max", "mac", "macbook", "macbook air", "macbook pro", "imac",
              "mac mini", "mac studio", "apple watch", "apple watch ultra", "apple pencil", "magic keyboard",
              "magic mouse", "magsafe", "lightning", "airtag", "apple tv", "homepod", "iphone case", "iphone cover",
              "ipad case", "ipad sleeve", "iphone screen protector", "iphone charger", "apple charger",
              "lightning cable", "apple cable", "apple adapter", "ipad keyboard", "apple tablet", "apple laptop",
              "apple earphones", "apple gift card", "applecare", "icloud", "app store", "itunes", "airpods tips",
              "apple watch band", "iphone stand"],
      es: ["apple", "apple store", "iphone", "iphone 15", "iphone 16", "iphone 17", "iphone 18", "iphone pro",
              "iphone pro max", "iphone reacondicionado", "ipad", "ipad air", "ipad pro", "ipad mini", "ipod",
              "airpods", "airpods pro", "airpods max", "mac", "macbook", "macbook air", "macbook pro", "imac",
              "mac mini", "mac studio", "apple watch", "apple watch ultra", "apple pencil", "magic keyboard",
              "magic mouse", "magsafe", "lightning", "airtag", "apple tv", "homepod", "funda iphone",
              "carcasa iphone", "funda ipad", "protector de pantalla iphone", "cargador iphone", "cargador apple",
              "cable lightning", "cable apple", "adaptador apple", "teclado ipad", "tableta apple",
              "portátil apple", "auriculares apple", "tarjeta regalo apple", "applecare", "icloud", "app store",
              "itunes", "correa apple watch", "soporte iphone"]
    }
  },
  jeuxSociete: {
    floors: ["-1"], icon: "dice",
    label: { fr: "Jeux de société", en: "Board games", es: "Juegos de mesa" },
    detail: { fr: "Près de l'escalier", en: "Near the stairs", es: "Cerca de la escalera" },
    keywords: {
      fr: ["jeu de société", "jeux de société", "jeu de plateau", "jeux de plateau", "puzzle", "puzzles",
              "puzzle 1000 pièces", "puzzle 3d", "jeu de cartes", "jeux de cartes", "cartes à jouer", "uno",
              "monopoly", "cluedo", "risk", "trivial pursuit", "scrabble", "times up", "loup-garou", "dixit",
              "catan", "colons de catane", "7 wonders", "azul", "carcassonne", "dobble", "jungle speed",
              "mille bornes", "petits chevaux", "escape game", "jeu de rôle", "donjons et dragons", "dé à jouer", "dés à jouer", "jeu de dés", "échecs",
              "jeu d'échecs", "dames", "backgammon", "tarot", "belote", "jeu d'ambiance", "jeu de soirée",
              "jeu coopératif", "jeu familial", "jeu pour enfant", "jeu éducatif", "jeu d'apéro",
              "rubik's cube", "maquette", "jeu en bois", "jouet"],
      en: ["board game", "board games", "tabletop game", "puzzle", "puzzles", "1000 piece puzzle", "3d puzzle",
              "card game", "card games", "playing cards", "uno", "monopoly", "cluedo", "risk", "trivial pursuit",
              "scrabble", "times up", "werewolf", "dixit", "catan", "settlers of catan", "7 wonders", "azul",
              "carcassonne", "dobble", "escape game", "role playing game", "dungeons and dragons", "dice", "chess",
              "chess set", "draughts", "backgammon", "party game", "family game", "cooperative game", "kids game",
              "educational game", "brain teaser", "rubiks cube", "model kit", "wooden game", "toy"],
      es: ["juego de mesa", "juegos de mesa", "juego de tablero", "puzle", "puzles", "rompecabezas",
              "puzle 1000 piezas", "puzle 3d", "juego de cartas", "juegos de cartas", "baraja", "uno", "monopoly",
              "cluedo", "risk", "trivial", "scrabble", "time's up", "hombre lobo", "dixit", "catan",
              "colonos de catán", "7 wonders", "azul", "carcassonne", "dobble", "escape room", "juego de rol",
              "dungeons and dragons", "dados", "ajedrez", "damas", "backgammon", "juego de fiesta",
              "juego familiar", "juego cooperativo", "juego infantil", "juego educativo", "cubo de rubik",
              "maqueta", "juguete"]
    }
  },
  savRetrait: {
    floors: ["-1"], icon: "wrench",
    // Priorité la plus haute : « mon iPhone est cassé » ou « je viens chercher
    // ma commande » doit mener au SAV, pas au rayon du produit cité.
    boost: 25,
    label: { fr: "SAV & retrait des colis", en: "After-sales & order pickup", es: "Posventa y recogida" },
    detail: { fr: "Réparations, retours, commandes", en: "Repairs, returns, orders", es: "Reparaciones, devoluciones, pedidos" },
    keywords: {
      fr: ["sav", "service après-vente", "après-vente", "réparation", "réparations", "réparer", "faire réparer",
              "atelier", "atelier de réparation", "diagnostic", "devis", "garantie", "extension de garantie",
              "assurance", "panne", "en panne", "ne marche pas", "ne fonctionne pas", "ne s'allume plus", "cassé", "cassée", "abîmée", "rayé",
              "abîmé", "écran cassé", "vitre cassée", "batterie hs", "dégât des eaux", "réparation smartphone",
              "réparation ordinateur", "changer un écran", "changer la batterie", "retour", "retour produit",
              "rendre un produit", "rembourser", "remboursement", "échange", "échanger", "rétractation",
              "produit défectueux", "réclamation", "litige", "duplicata de facture", "retrait",
              "retrait de commande", "retirer ma commande", "récupérer ma commande", "chercher ma commande",
              "click and collect", "commande", "commande en ligne", "point retrait", "suivi de commande", "colis",
              "paquet", "dépannage", "assistance", "installation à domicile", "transfert de données", "sauvegarde",
              "mise à jour", "nettoyage appareil",
              "ça rame", "ordinateur lent", "lent", "ralenti", "ça plante", "plante", "bug", "bugue", "virus", "écran bleu", "ne charge plus", "ne s'allume pas", "ne s'éteint plus", "surchauffe", "problème", "souci", "aide technique", "ça ne marche plus", "ça a lâché", "hors service", "carte mère grillée", "récupérer mes données", "données perdues",
              "ordinateur rame", "pc rame", "téléphone rame", "portable rame", "tablette rame", "il rame", "elle rame", "ordinateur plante", "téléphone plante", "batterie ne tient plus", "batterie se vide vite", "écran noir", "plus de son", "ne s'affiche plus", "ne se connecte plus"],
      en: ["after-sales", "after sales", "customer service", "service desk", "repair", "repairs", "fix",
              "repair shop", "diagnosis", "quote", "warranty", "extended warranty", "insurance", "fault",
              "not working", "doesn't work", "won't turn on", "broken", "damaged", "broken screen",
              "cracked screen", "dead battery", "water damage", "phone repair", "computer repair",
              "screen replacement", "battery replacement", "return", "return a product", "refund", "exchange",
              "faulty product", "complaint", "invoice copy", "pickup", "order pickup", "pick up my order",
              "collect my order", "click and collect", "order", "online order", "collection point",
              "order tracking", "parcel", "package", "tech support", "support", "data transfer", "backup",
              "software update",
              "slow computer", "very slow", "freezes", "crashes", "bug", "virus", "blue screen", "won't charge", "doesn't charge", "overheating", "problem", "issue", "stopped working", "out of order", "lost data", "recover my data",
              "computer is slow", "phone is slow", "laptop is slow", "battery drains fast", "black screen", "no sound", "won't connect"],
      es: ["servicio técnico", "posventa", "atención al cliente", "reparación", "reparaciones", "reparar", "taller",
              "diagnóstico", "presupuesto", "garantía", "extensión de garantía", "seguro", "avería", "no funciona",
              "no enciende", "roto", "dañado", "pantalla rota", "batería agotada", "daño por agua",
              "reparación de móvil", "reparación de ordenador", "cambiar la pantalla", "cambiar la batería",
              "devolución", "devolver un producto", "reembolso", "cambio", "producto defectuoso", "reclamación",
              "copia de factura", "recogida", "recoger pedido", "recoger mi pedido", "click and collect", "pedido",
              "pedido online", "punto de recogida", "seguimiento del pedido", "paquete", "soporte técnico",
              "asistencia", "transferencia de datos", "copia de seguridad", "actualización",
              "va lento", "se cuelga", "se bloquea", "virus", "pantalla azul", "no carga", "se calienta", "problema", "dejó de funcionar", "fuera de servicio", "recuperar mis datos", "datos perdidos",
              "el ordenador va lento", "el móvil va lento", "la batería se agota", "pantalla negra", "sin sonido", "no se conecta"]
    }
  },
  caisse: {
    floors: ["-1"], icon: "card",
    label: { fr: "Caisses", en: "Checkout", es: "Caja" },
    detail: { fr: "Paiement", en: "Payment", es: "Pago" },
    keywords: {
      fr: ["caisse", "caisses", "payer", "où payer", "paiement", "encaissement", "carte bancaire", "cb", "espèces",
              "liquide", "sans contact", "ticket", "ticket de caisse", "facture", "détaxe", "tax free",
              "carte cadeau", "chèque cadeau", "bon d'achat", "avoir", "trois fois sans frais",
              "paiement en plusieurs fois", "financement", "crédit", "emballage cadeau", "papier cadeau",
              "file d'attente", "caisse automatique", "borne de paiement", "réservation"],
      en: ["checkout", "cashier", "till", "cash register", "pay", "where to pay", "payment", "card payment",
              "credit card", "cash", "contactless", "receipt", "invoice", "tax free", "gift card", "gift voucher",
              "voucher", "credit note", "instalments", "pay in instalments", "financing", "gift wrapping", "queue",
              "self checkout"],
      es: ["caja", "cajas", "pagar", "dónde pagar", "pago", "tarjeta bancaria", "efectivo", "contactless", "ticket",
              "recibo", "factura", "tax free", "tarjeta regalo", "cheque regalo", "vale", "financiación",
              "pago a plazos", "envoltorio de regalo", "papel de regalo", "cola", "caja automática"]
    }
  },
  adhesion: {
    floors: ["-1"], icon: "person",
    label: { fr: "Adhésion", en: "Membership", es: "Socios" },
    detail: { fr: "Carte Fnac, avantages", en: "Fnac card, benefits", es: "Tarjeta Fnac, ventajas" },
    keywords: {
      fr: ["adhésion", "adhérent", "devenir adhérent", "carte fnac", "carte adhérent", "carte de fidélité",
              "fidélité", "points fidélité", "avantages adhérent", "réduction adhérent", "offre adhérent",
              "abonnement", "fnac plus", "renouveler ma carte", "inscription", "s'inscrire", "compte fnac",
              "espace adhérent", "parrainage", "carte trois ans", "carte un an"],
      en: ["membership", "member", "become a member", "fnac card", "member card", "loyalty card", "loyalty points",
              "member benefits", "member discount", "subscription", "fnac plus", "renew my card", "sign up",
              "fnac account", "referral"],
      es: ["socio", "hacerse socio", "membresía", "tarjeta fnac", "tarjeta de socio", "tarjeta de fidelidad",
              "puntos de fidelidad", "ventajas para socios", "descuento socio", "suscripción", "fnac plus",
              "renovar la tarjeta", "darse de alta", "cuenta fnac"]
    }
  }
};

// Produits éditoriaux : ils ne sont pas vendus ici mais à la Fnac Wilson.
// Jeanne indique l'adresse au lieu de montrer un rayon (external: true).
export const OTHER_STORE = {
  name: "Fnac Wilson",
  address: ["16, allées Franklin-Roosevelt", "31000 Toulouse"]
};

ZONES.editorial = {
  external: true, floors: [], icon: "book",
  label: { fr: "Livres, CD, vinyles, DVD (Fnac Wilson)", en: "Books, CDs, vinyl, DVDs (Fnac Wilson)", es: "Libros, CD, vinilos, DVD (Fnac Wilson)" },
  detail: { fr: "", en: "", es: "" },
  keywords: {
    fr: ["livre", "livres", "roman", "romans", "poche", "livre de poche", "polar", "thriller", "science-fiction",
            "fantasy", "bd", "bande dessinée", "bandes dessinées", "manga", "mangas", "comics", "one piece",
            "naruto", "livre jeunesse", "livre enfant", "album jeunesse", "manuel scolaire", "livre scolaire",
            "parascolaire", "annales", "cahier de vacances", "dictionnaire", "encyclopédie", "atlas",
            "guide de voyage", "routard", "lonely planet", "livre audio", "livre de cuisine", "beau livre",
            "biographie", "essai", "développement personnel", "poésie", "théâtre", "goncourt",
            "nouveauté littéraire", "dédicace", "cd", "cd audio", "album", "compilation", "vinyle", "vinyles",
            "disque vinyle", "33 tours", "45 tours", "coffret cd", "dvd", "blu-ray", "4k ultra hd", "coffret dvd",
            "série", "saison", "film", "bande originale", "cassette", "presse", "magazine", "journal",
            "abonnement presse"],
    en: ["book", "books", "novel", "novels", "paperback", "crime novel", "thriller", "science fiction", "fantasy",
            "comic", "comic book", "comics", "graphic novel", "manga", "one piece", "naruto", "children's book",
            "kids book", "textbook", "school book", "dictionary", "encyclopedia", "atlas", "travel guide",
            "lonely planet", "audiobook", "cookbook", "biography", "essay", "poetry", "cd", "album", "compilation",
            "vinyl", "vinyl record", "record", "lp", "cd box set", "dvd", "blu-ray", "4k ultra hd", "dvd box set",
            "series", "season", "film", "movie", "soundtrack", "magazine", "newspaper", "press"],
    es: ["libro", "libros", "novela", "novelas", "bolsillo", "novela negra", "thriller", "ciencia ficción",
            "fantasía", "cómic", "cómics", "novela gráfica", "manga", "one piece", "naruto", "libro infantil",
            "libro de texto", "diccionario", "enciclopedia", "atlas", "guía de viaje", "lonely planet",
            "audiolibro", "libro de cocina", "biografía", "ensayo", "poesía", "cd", "álbum", "recopilatorio",
            "vinilo", "vinilos", "disco de vinilo", "dvd", "blu-ray", "4k ultra hd", "serie", "temporada",
            "película", "banda sonora", "revista", "periódico", "prensa"]
  }
};

// Boutons de recherches fréquentes (page principale).
export const SUGGESTIONS = [
  { zone: "audio", icon: "headphones", label: { fr: "Casques audio", en: "Headphones", es: "Auriculares" } },
  { zone: "gaming", icon: "gamepad", label: { fr: "Consoles", en: "Consoles", es: "Consolas" } },
  { zone: "apple", icon: "apple", label: { fr: "iPhone", en: "iPhone", es: "iPhone" } },
  { zone: "tv", icon: "tv", label: { fr: "TV", en: "TV", es: "TV" } },
  { zone: "savRetrait", icon: "wrench", label: { fr: "SAV", en: "Repairs", es: "Posventa" } },
  { zone: "savRetrait", icon: "package", label: { fr: "Retrait commande", en: "Order pickup", es: "Recoger pedido" } }
];

// Petites intentions de conversation (quand aucun rayon ne correspond).
export const INTENTS = {
  hello: ["bonjour", "salut", "bonsoir", "hello", "hi", "hey", "good morning", "hola", "buenos dias", "buenas tardes"],
  thanks: ["merci", "merci beaucoup", "thank you", "thanks", "gracias", "muchas gracias"],
  human: ["vendeur", "vendeuse", "conseiller", "conseillere", "quelqu un", "aide", "staff", "someone", "assistant", "employee", "help", "vendedor", "vendedora", "dependiente", "ayuda"]
};
