const dictionary = {
 fr:{demoLabel:"DÉMONSTRATEUR • TOULOUSE",online:"Disponible maintenant",assistantRole:"Votre guide en magasin",portraitNote:"Personnage virtuel original · Maquette interne",eyebrow:"BIENVENUE À LA FNAC JEANNE D'ARC",title:"Comment puis-je vous aider ?",subtitle:"Dites-moi ce que vous cherchez, je vous guide vers le bon rayon.",welcome:"Bonjour ! Je suis Jeanne, votre guide en magasin. Que recherchez-vous aujourd’hui ?",inputPlaceholder:"Ex. Où sont les disques durs ?",microLabel:"Appuyez pour parler",listening:"Je vous écoute…",speechHint:"Vous pouvez aussi écrire votre question ci-dessus.",voiceOn:"Voix activée",voiceOff:"Voix désactivée",suggestions:["Où sont les disques durs ?","Je cherche un casque audio","Où trouver les vinyles ?"],found:"Je vous guide vers",where:"OÙ ALLER",route:"Voir le chemin",unknown:"Je n’ai pas encore trouvé ce produit dans cette démonstration. Un conseiller pourra vous renseigner ; ou essayez « disque dur », « livre », « casque », « vinyle » ou « téléphone ».",user:"VOUS",assistant:"JEANNE"},
 en:{demoLabel:"DEMONSTRATOR • TOULOUSE",online:"Available now",assistantRole:"Your in-store guide",portraitNote:"Original virtual character · Internal mock-up",eyebrow:"WELCOME TO FNAC JEANNE D'ARC",title:"How can I help you?",subtitle:"Tell me what you are looking for and I will guide you to the right department.",welcome:"Hello! I’m Jeanne, your in-store guide. What are you looking for today?",inputPlaceholder:"For example: Where are hard drives?",microLabel:"Tap to speak",listening:"I’m listening…",speechHint:"You can also type your question above.",voiceOn:"Voice on",voiceOff:"Voice off",suggestions:["Where are hard drives?","I’m looking for headphones","Where can I find vinyl?"],found:"Let me guide you to",where:"WHERE TO GO",route:"Show route",unknown:"I haven’t found that product in this demonstration yet. A member of staff can help; or try “hard drive”, “book”, “headphones”, “vinyl” or “phone”.",user:"YOU",assistant:"JEANNE"},
 es:{demoLabel:"DEMOSTRADOR • TOULOUSE",online:"Disponible ahora",assistantRole:"Tu guía en tienda",portraitNote:"Personaje virtual original · Maqueta interna",eyebrow:"BIENVENIDO A FNAC JEANNE D'ARC",title:"¿Cómo puedo ayudarte?",subtitle:"Dime lo que buscas y te guiaré a la sección correcta.",welcome:"¡Hola! Soy Jeanne, tu guía en tienda. ¿Qué buscas hoy?",inputPlaceholder:"Por ejemplo: ¿Dónde están los discos duros?",microLabel:"Pulsa para hablar",listening:"Te escucho…",speechHint:"También puedes escribir tu pregunta arriba.",voiceOn:"Voz activada",voiceOff:"Voz desactivada",suggestions:["¿Dónde están los discos duros?","Busco auriculares","¿Dónde encuentro vinilos?"],found:"Te guío a",where:"DÓNDE IR",route:"Ver el camino",unknown:"Todavía no encuentro ese producto en esta demostración. Un vendedor puede ayudarte; o prueba « disco duro », « libro », « auriculares », « vinilo » o « teléfono ».",user:"TÚ",assistant:"JEANNE"}
};
let lang = 'fr', voice = true, recognition;
const $ = s => document.querySelector(s), text = () => dictionary[lang];
function renderLanguage(){
 document.documentElement.lang=lang; document.querySelectorAll('[data-i18n]').forEach(e=>e.textContent=text()[e.dataset.i18n]); document.querySelectorAll('[data-i18n-placeholder]').forEach(e=>e.placeholder=text()[e.dataset.i18nPlaceholder]);
 $('#welcome-message').textContent=text().welcome; document.querySelector('.assistant .message-label').textContent=text().assistant;
 document.querySelectorAll('.lang').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang)); renderSuggestions();
}
function renderSuggestions(){ $('#suggestions').innerHTML=text().suggestions.map(s=>`<button type="button">${s}</button>`).join(''); $('#suggestions').querySelectorAll('button').forEach(b=>b.onclick=()=>ask(b.textContent)); }
function speak(message){ if(!voice || !('speechSynthesis' in window)) return; speechSynthesis.cancel(); const utterance=new SpeechSynthesisUtterance(message); utterance.lang={fr:'fr-FR',en:'en-GB',es:'es-ES'}[lang]; utterance.rate=.98; speechSynthesis.speak(utterance); }
function say(message, product){
 $('#conversation').insertAdjacentHTML('beforeend',`<article class="message assistant new"><span class="message-label">${text().assistant}</span><p>${message}</p></article>`); $('#conversation').scrollTop=$('#conversation').scrollHeight; $('#avatar').classList.add('speaking'); setTimeout(()=>$('#avatar').classList.remove('speaking'), Math.min(3500, message.length*35)); speak(message);
 if(product) showLocation(product); else $('#location-card').classList.add('hidden');
}
function showLocation(p){ const t=text(), name=p.name[lang], msg=`${t.found} ${name}. ${p.level[lang]}, ${p.aisle[lang]}. ${p.detail[lang]}.`;
 $('#location-card').className='location-card'; $('#location-card').innerHTML=`<div><span class="map-pin">${p.zone}</span><div><small>${t.where}</small><strong>${p.level[lang]} · ${p.aisle[lang]}</strong><p>${p.detail[lang]}</p></div></div><button id="route" type="button">${t.route} <b>→</b></button>`;
 $('#route').onclick=()=>openRoute(p); return msg;
}
function openRoute(p){ const card=$('#location-card'); card.innerHTML=`<div class="route"><div class="mini-map"><span class="entrance">●</span><span class="zone zone-a">A</span><span class="zone zone-b">B</span><span class="zone zone-c">C</span><span class="zone zone-d">D</span><span class="zone zone-e">E</span><i class="path path-${p.zone}"></i></div><div><small>${text().where}</small><strong>${p.zone} · ${p.aisle[lang]}</strong><p>${p.detail[lang]}</p></div></div>`; }
function ask(question){ if(!question.trim()) return; $('#question').value=''; $('#conversation').insertAdjacentHTML('beforeend',`<article class="message user"><span class="message-label">${text().user}</span><p>${question}</p></article>`); const q=question.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,''); const product=STORE_PRODUCTS.find(p=>p.keywords.some(k=>q.includes(k))); setTimeout(()=>{ if(product){ const t=text(), msg=`${t.found} ${product.name[lang]}. ${product.level[lang]}, ${product.aisle[lang]}. ${product.detail[lang]}.`; say(msg,product); } else say(text().unknown); },450); }
document.querySelectorAll('.lang').forEach(b=>b.onclick=()=>{lang=b.dataset.lang; renderLanguage();});
$('#question-form').onsubmit=e=>{e.preventDefault(); ask($('#question').value);};
$('#toggle-voice').onclick=()=>{voice=!voice; $('#toggle-voice').innerHTML=`${voice?'🔊':'🔇'} <span>${text()[voice?'voiceOn':'voiceOff']}</span>`;};
$('#fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen?.();
function setupRecognition(){ const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition; if(!SpeechRecognition){$('#speech-hint').textContent=text().speechHint; return;} recognition=new SpeechRecognition(); recognition.interimResults=false; recognition.maxAlternatives=1; recognition.onresult=e=>{ $('#microphone').classList.remove('listening'); $('#mic-label').textContent=text().microLabel; ask(e.results[0][0].transcript); }; recognition.onerror=()=>{ $('#microphone').classList.remove('listening'); $('#mic-label').textContent=text().microLabel; }; recognition.onend=()=>$('#microphone').classList.remove('listening'); }
$('#microphone').onclick=()=>{ if(!recognition) return; recognition.lang={fr:'fr-FR',en:'en-GB',es:'es-ES'}[lang]; $('#microphone').classList.add('listening'); $('#mic-label').textContent=text().listening; recognition.start(); };
renderLanguage(); setupRecognition();
