/* Plan de démonstration d'après la description de Guillaume — à valider en magasin. */
const tr=(fr,en,es)=>({fr,en,es});
const item=(keywords,name,zone,aisle,level,detail,route)=>({keywords,name:tr(name,name,name),zone,aisle:tr(aisle,aisle,aisle),level:tr(level,level,level),detail:tr(detail,detail,detail),route:tr(route,route,route)});
window.STORE_PRODUCTS=[
 item(["telephone android","android","samsung","xiaomi","google pixel","smartphone"],"Smartphones Android","T","Téléphonie","Entrée · rez-de-chaussée","Espace téléphonie, juste devant la borne","Vous y êtes presque : l’espace téléphonie est à l’entrée."),
 item(["chargeur","charger","cargador","cable telephone","câble téléphone","ecouteur telephone","écouteur téléphone"],"Accessoires téléphonie","T","Téléphonie","Entrée · rez-de-chaussée","Chargeurs, câbles et écouteurs dans l’espace entrée","Restez dans l’espace téléphonie à l’entrée."),
 item(["iphone","apple","mac","macbook","ipad"],"Univers Apple","A","Ligne gauche · Apple","Sous-sol","En descendant l’escalier, première zone de la ligne gauche","Prenez l’escalier à droite en entrant. Au sous-sol, allez sur la première zone à gauche."),
 item(["enceinte","son","audio","casque audio","headphone","auriculares","speaker","haut parleur","haut-parleur"],"Son & audio","S","Ligne gauche · Son","Sous-sol","Deuxième zone de la ligne gauche, après Apple","Descendez l’escalier à droite. Au sous-sol, suivez la ligne gauche après l’univers Apple."),
 item(["television","télévision","tv","televiseur","téléviseur","ecran tv","écran tv"],"Télévisions","V","Ligne gauche · Télévisions","Sous-sol","Au fond de la ligne gauche","Descendez l’escalier à droite, puis allez jusqu’au fond de la ligne gauche."),
 item(["tablette android","tablette","tablet","ordinateur windows","pc windows","laptop"],"Tablettes Android & PC Windows","W","Ligne centrale · Informatique","Sous-sol","Début de la ligne centrale","Descendez l’escalier à droite. Au sous-sol, prenez le début de la rangée centrale."),
 item(["ecran ordinateur","écran ordinateur","monitor","moniteur","pantalla ordenador","pantalla"],"Écrans d’ordinateur","M","Ligne centrale · Écrans","Sous-sol","Milieu de la ligne centrale","Descendez au sous-sol puis avancez dans la rangée centrale, après les tablettes et PC Windows."),
 item(["photo","camera","appareil photo","camara","cámara","objectif"],"Photo","P","Ligne centrale · Photo","Sous-sol","Au fond de la ligne centrale","Descendez l’escalier à droite puis allez au fond de la rangée centrale."),
 item(["caisse","caisses","checkout","cashier","caja"],"Caisses","C","Ligne droite · Caisses","Sous-sol","Tout de suite à droite en arrivant au sous-sol","Descendez l’escalier à droite : les caisses sont immédiatement à votre droite."),
 item(["cle usb","clé usb","usb","disque dur","hard drive","disco duro","ssd","imprimante","printer","impresora","cable pc","câble pc"],"Accessoires PC & impression","I","Ligne droite · Accessoires PC","Sous-sol","Après les caisses sur la ligne droite","Descendez au sous-sol. Après les caisses, suivez la ligne de droite vers les accessoires PC."),
 item(["gaming","pc gaming","razer","logitech","souris","mouse","clavier","keyboard","micro gaming","casque gaming"],"PC Gaming","G","Ligne droite · PC Gaming","Sous-sol","Accessoires, souris, claviers, casques et micros","Descendez au sous-sol, puis continuez sur la ligne de droite après les accessoires PC."),
 item(["playstation","nintendo","xbox","console","gaming console","consola"],"Consoles & jeux vidéo","J","Ligne droite · Consoles","Sous-sol","Au fond de la ligne droite","Descendez l’escalier puis allez jusqu’au fond de la ligne droite, après le PC Gaming.")
];
