// Vérifie que les phrases des clients mènent au bon rayon.
// Lancer depuis le dossier du projet :  node tests/search.test.mjs
import { findZone, findZoneDetailed, findInfo, findIntent, findClarify, pickClarifyOption } from "../js/search.js";

const cases = [
  // [langue, phrase, rayon attendu]
  ["fr", "je recherche un chargeur d'iPhone", "apple"],
  ["fr", "chargeur d'iPhone", "apple"],
  ["fr", "une coque pour iPhone 15", "apple"],
  ["fr", "un câble USB-C pour iPad", "apple"],
  ["fr", "des écouteurs Apple", "apple"],
  ["fr", "un chargeur Samsung", "telephonie"],
  ["fr", "un chargeur de téléphone", "telephonie"],
  ["fr", "je voudrais savoir où sont les casques", "audio"],
  ["fr", "où est la télécommande de la TV", "tv"],
  ["fr", "un micro-ondes", "electromenager"],
  ["fr", "une machine à café", "electromenager"],
  ["fr", "un casque de trottinette", "trottinettes"],
  ["fr", "un disque vinyle", "editorial"],
  ["fr", "une platine vinyle", "audio"],
  ["fr", "une souris gaming", "accessoiresGaming"],
  ["fr", "je cherche une PS5", "gaming"],
  ["fr", "des LEGO", "escalier"],
  ["fr", "retirer ma commande", "savRetrait"],
  ["fr", "un câble HDMI", "informatique"],
  ["fr", "une clé USB", "informatique"],
  ["fr", "un PC portable", "pcwindows"],
  ["fr", "des écouteurs sans fil", "audio"],
  ["fr", "un appareil photo", "photo"],
  ["fr", "la carte de fidélité", "adhesion"],
  ["fr", "un jeu de société", "jeuxSociete"],
  ["fr", "des AirPods", "apple"],
  ["fr", "les toilettes", null],
  // Fautes d'orthographe et mauvaise reconnaissance vocale
  ["fr", "un aifone", "apple"],
  ["fr", "une playstasion 5", "gaming"],
  ["fr", "une play station", "gaming"],
  ["fr", "des écoutteurs", "audio"],
  ["fr", "une télévition", "tv"],
  ["fr", "une trotinete électrique", "trottinettes"],
  ["fr", "une souri", "accessoiresGaming"],
  ["fr", "un samsoung", "telephonie"],
  ["fr", "mon écran est cassé", "savRetrait"],
  ["fr", "un portable", "telephonie"],
  // Nouveaux rayons du plan réel
  ["fr", "une montre connectée", "objets"],
  ["fr", "un aspirateur balai", "electromenager"],
  ["fr", "une cartouche d'encre", "cartouches"],
  ["fr", "un PC gamer", "accessoiresGaming"],
  ["fr", "une tablette Android", "tablettes"],
  ["fr", "une imprimante", "informatique"],
  ["fr", "un micro cravate", "photo"],
  ["fr", "une carte Pokémon", "escalier"],
  ["fr", "la carte adhérent", "adhesion"],
  ["fr", "où sont les caisses", "caisse"],
  ["fr", "retirer un colis", "savRetrait"],
  // Produits éditoriaux → Fnac Wilson
  ["fr", "bonjour, où est-ce que je peux trouver des livres ?", "editorial"],
  ["fr", "un manuel scolaire", "editorial"],
  ["fr", "des mangas", "editorial"],
  ["fr", "le dernier album en CD", "editorial"],
  ["fr", "un DVD", "editorial"],
  ["fr", "des vinyles", "editorial"],
  ["en", "where can I find books", "editorial"],
  ["es", "busco un libro", "editorial"],
  // Ne doit rien trouver
  ["fr", "une table", null],
  ["fr", "passer un appel", null],
  ["fr", "je cherche mes clés", null],
  ["en", "an iPhone charger", "apple"],
  ["en", "a charger for my iPhone", "apple"],
  ["en", "where are the headphones", "audio"],
  ["es", "un cargador de iPhone", "apple"],
  ["es", "¿dónde están los auriculares?", "audio"],
  ["es", "el mando a distancia", "tv"],
  // --- Priorité du SAV : la panne passe avant le rayon du produit ---
  ["fr", "je viens faire réparer mon iPhone", "savRetrait"],
  ["fr", "mon iPhone est cassé", "savRetrait"],
  ["fr", "ma télé est cassée", "savRetrait"],
  ["fr", "je viens chercher ma commande", "savRetrait"],
  ["fr", "une extension de garantie", "savRetrait"],
  ["fr", "mon aspirateur ne fonctionne pas", "savRetrait"],
  ["en", "I want to pick up my order", "savRetrait"],
  ["es", "vengo a recoger mi pedido", "savRetrait"],
  // mais le produit seul reste dans son rayon
  ["fr", "un iPhone 17", "apple"],
  ["fr", "une télé 65 pouces", "tv"],

  // --- Vocabulaire ajouté : étage 0 ---
  ["fr", "une montre Garmin", "objets"],
  ["fr", "une ampoule connectée", "objets"],
  ["fr", "un babyphone", "objets"],
  ["fr", "une batterie externe", "telephonie"],
  ["fr", "un verre trempé pour Samsung", "telephonie"],
  ["fr", "une carte SIM", "telephonie"],
  ["fr", "des cartes Pokémon", "escalier"],
  ["fr", "un LEGO Technic", "escalier"],
  ["fr", "une figurine Funko Pop", "escalier"],

  // --- Vocabulaire ajouté : sous-sol ---
  ["fr", "un jeu Pokémon", "gaming"],
  ["fr", "une manette PS5", "gaming"],
  ["fr", "un casque VR", "gaming"],
  ["fr", "un clavier mécanique", "accessoiresGaming"],
  ["fr", "une cartouche d'encre HP", "cartouches"],
  ["fr", "une carte graphique RTX", "accessoiresGaming"],
  ["fr", "un airfryer", "electromenager"],
  ["fr", "une friteuse sans huile", "electromenager"],
  ["fr", "un robot pâtissier", "electromenager"],
  ["fr", "une brosse à dents électrique", "electromenager"],
  ["fr", "un disque dur externe", "informatique"],
  ["fr", "une imprimante laser", "informatique"],
  ["fr", "un répéteur wifi", "informatique"],
  ["fr", "une tablette Samsung", "tablettes"],
  ["fr", "une trottinette électrique", "trottinettes"],
  ["fr", "un casque de vélo", "trottinettes"],
  ["fr", "un objectif pour mon appareil photo", "photo"],
  ["fr", "une carte SD", "photo"],
  ["fr", "un micro cravate", "photo"],
  ["fr", "un vidéoprojecteur", "tv"],
  ["fr", "une télécommande universelle", "tv"],
  ["fr", "des écouteurs sans fil", "audio"],
  ["fr", "une enceinte bluetooth", "audio"],
  ["fr", "un casque à réduction de bruit", "audio"],
  ["fr", "un AirTag", "apple"],
  ["fr", "un bracelet Apple Watch", "apple"],
  ["fr", "un dé à jouer", "jeuxSociete"],
  ["fr", "un puzzle 1000 pièces", "jeuxSociete"],
  ["fr", "un jeu de rôle", "jeuxSociete"],
  ["fr", "la carte Fnac", "adhesion"],
  ["fr", "où payer", "caisse"],
  ["fr", "un manuel scolaire", "editorial"],
  ["fr", "un magazine", "editorial"],

  // --- Fautes de frappe et d'oreille ---
  ["fr", "une trotinette", "trottinettes"],
  ["fr", "un aspirateur robo", "electromenager"],

  // --- Anglais et espagnol ajoutés ---
  ["en", "a gaming keyboard", "accessoiresGaming"],
  ["en", "a robot vacuum", "electromenager"],
  ["en", "an ink cartridge", "cartouches"],
  ["en", "wireless earbuds", "audio"],
  ["en", "a smart bulb", "objets"],
  ["es", "un cargador de móvil", "telephonie"],
  ["es", "auriculares inalámbricos", "audio"],
  ["es", "una freidora de aire", "electromenager"],
  ["es", "un disco duro externo", "informatique"],
  ["es", "cartas pokemon", "escalier"],
  // --- À l'oral : la reconnaissance vocale écrit les nombres en lettres
  //     et sépare les marques (« PS cinq », « air pods »). ---
  ["fr", "je veux une PS cinq", "gaming"],
  ["fr", "la Switch deux", "gaming"],
  ["fr", "une play station", "gaming"],
  ["fr", "Xbox Série X", "gaming"],
  ["fr", "un iPhone quinze", "apple"],
  ["fr", "un iPhone dix-sept", "apple"],
  ["fr", "des air pods", "apple"],
  ["fr", "un i phone", "apple"],
  ["fr", "une télé soixante-cinq pouces", "tv"],
  ["fr", "une télé de cinquante-cinq pouces", "tv"],
  ["fr", "un écran vingt-sept pouces", "accessoiresGaming"],
  ["fr", "un puzzle mille pièces", "jeuxSociete"],
  ["fr", "un dé à jouer", "jeuxSociete"],
  ["fr", "un jeu de dés", "jeuxSociete"],
  ["fr", "un go pro", "photo"],
  // les mots qui ressemblent ne doivent pas être emportés
  ["fr", "un coffret de séries DVD", "editorial"],
  ["fr", "le jeu Uno", "jeuxSociete"],
  ["fr", "des capsules de café", "electromenager"],
  ["en", "a play station five", "gaming"],
  ["es", "una tele de sesenta y cinco pulgadas", "tv"],
  ["fr", "un écran de cent quarante-quatre hertz", "accessoiresGaming"],
  ["fr", "je cherche le rayon informatique", "pcwindows"],
  ["fr", "un casque anti bruit", "audio"],
  ["fr", "une carte mémoire pour ma switch", "gaming"],
  ["fr", "un iphone seize pro max", "apple"],
  // --- Phrases de clients, telles qu'on les dit à voix haute ---
  // Panne, retour ou colis : le SAV, même si la phrase cite un produit.
  ["fr", "ouais je viens parce que mon iPhone est cassé", "savRetrait"],
  ["fr", "mon iPhone ne marche plus", "savRetrait"],
  ["fr", "mon iphone marche plus", "savRetrait"],
  ["fr", "mon iPhone 16 pro max est cassé", "savRetrait"],
  ["fr", "l'écran de mon iPhone est fissuré", "savRetrait"],
  ["fr", "j'ai fait tomber mon téléphone", "savRetrait"],
  ["fr", "mon téléphone est tombé dans l'eau", "savRetrait"],
  ["fr", "je veux rendre ma télé", "savRetrait"],
  ["fr", "j'ai acheté un casque il marche pas", "savRetrait"],
  ["fr", "ma machine à café fuit", "savRetrait"],
  ["fr", "ma PS5 fait un bruit bizarre", "savRetrait"],
  ["fr", "ma manette drift", "savRetrait"],
  ["fr", "mon ordi s'allume pas", "savRetrait"],
  ["fr", "mon pc portable chauffe beaucoup", "savRetrait"],
  ["fr", "je viens récupérer mon ordinateur", "savRetrait"],
  ["fr", "je viens déposer mon ordinateur en réparation", "savRetrait"],
  ["fr", "j'ai commandé sur internet", "savRetrait"],
  ["fr", "j'ai reçu un SMS pour retirer mon colis", "savRetrait"],
  ["fr", "ma commande fnac.com est arrivée", "savRetrait"],
  ["fr", "je voudrais échanger ce casque", "savRetrait"],
  ["fr", "je veux me faire rembourser", "savRetrait"],
  ["fr", "ça me plaît pas je voudrais le rapporter", "savRetrait"],
  ["fr", "l'écran de ma télé a des lignes", "savRetrait"],
  ["fr", "mon airpods droit ne marche plus", "savRetrait"],
  ["fr", "ma batterie est gonflée", "savRetrait"],
  ["fr", "j'ai oublié mon code", "savRetrait"],
  ["fr", "mon téléphone est bloqué", "savRetrait"],
  ["fr", "ma trottinette ne démarre plus", "savRetrait"],
  ["fr", "mes écouteurs grésillent", "savRetrait"],
  ["fr", "ma switch ne lit plus les jeux", "savRetrait"],
  ["fr", "mon iPad ne charge plus", "savRetrait"],
  ["fr", "je viens chercher mon iPhone réparé", "savRetrait"],
  ["en", "my iPhone is broken", "savRetrait"],
  ["en", "my laptop won't turn on", "savRetrait"],
  ["en", "I want to return these headphones", "savRetrait"],
  ["es", "mi móvil no funciona", "savRetrait"],
  ["es", "quiero devolver este producto", "savRetrait"],
  ["fr", "je cherche un iPhone 16 pro max", "apple"],
  ["fr", "je viens chercher un iPhone", "apple"],
  ["fr", "un chargeur qui charge plus vite pour iPhone", "apple"],
  ["fr", "une batterie externe qui tient plus longtemps", "telephonie"],
  ["fr", "un verre trempé pour mon téléphone", "telephonie"],
  ["fr", "pour écouter de la musique", "audio"],
  ["fr", "une JBL Flip", "audio"],
  ["fr", "des Galaxy Buds", "audio"],
  ["fr", "un casque pour la télé", "audio"],
  ["fr", "la play 5", "gaming"],
  ["fr", "une Switch 2 avec Mario Kart", "gaming"],
  ["fr", "une carte PSN", "gaming"],
  ["fr", "des jeux pour la switch", "gaming"],
  ["fr", "une carte Roblox", "gaming"],
  ["fr", "des cartes Lorcana", "escalier"],
  ["fr", "un bouquet de fleurs LEGO", "escalier"],
  ["fr", "une Pop One Piece", "escalier"],
  ["fr", "un Skyjo", "jeuxSociete"],
  ["fr", "les aventuriers du rail", "jeuxSociete"],
  ["fr", "un puissance 4", "jeuxSociete"],
  ["fr", "une Dyson V15", "electromenager"],
  ["fr", "un Airwrap Dyson", "electromenager"],
  ["fr", "un Ninja Creami", "electromenager"],
  ["fr", "une bouilloire électrique", "electromenager"],
  ["fr", "des capsules Vertuo", "electromenager"],
  ["fr", "un cuiseur à riz", "electromenager"],
  ["fr", "une tablette Lenovo", "tablettes"],
  ["fr", "un stylet pour tablette", "tablettes"],
  ["fr", "une Kindle", "liseuses"],
  ["fr", "un ordinateur pour mes études", "pcwindows"],
  ["fr", "un PC portable 15 pouces", "pcwindows"],
  ["fr", "Microsoft Office", "pcwindows"],
  ["fr", "une télé 50 pouces", "tv"],
  ["fr", "une Samsung The Frame", "tv"],
  ["fr", "un grand écran pour le salon", "tv"],
  ["fr", "une Instax mini 12", "photo"],
  ["fr", "des pellicules Instax", "photo"],
  ["fr", "un DJI Osmo Pocket 3", "photo"],
  ["fr", "un micro pour mon téléphone", "photo"],
  ["fr", "un ring light", "photo"],
  ["fr", "une webcam", "accessoiresGaming"],
  ["fr", "une RTX 5070", "accessoiresGaming"],
  ["fr", "une carte mémoire", "informatique"],
  ["fr", "améliorer mon wifi", "informatique"],
  ["fr", "une multiprise", "informatique"],
  ["fr", "de l'encre pour mon imprimante", "cartouches"],
  ["fr", "une cartouche HP 305", "cartouches"],
  ["fr", "une trottinette Xiaomi", "trottinettes"],
  ["fr", "un vélo électrique", "trottinettes"],
  ["fr", "payer en 4 fois sans frais", "adhesion"],
  ["fr", "la carte Fnac+", "adhesion"],
  ["fr", "payer en espèces", "caisse"],
  ["fr", "un roman policier", "editorial"],
  ["fr", "bonjour mon Samsung s'éteint tout seul", "savRetrait"],
  ["fr", "ma télé a plus de son", "savRetrait"],
  ["fr", "mon casque bluetooth se connecte plus", "savRetrait"],
  ["fr", "j'ai un problème avec mon ordinateur", "savRetrait"],
  ["fr", "le bouton de ma manette est cassé", "savRetrait"],
  ["fr", "je viens pour la garantie de mon aspirateur", "savRetrait"],
  ["fr", "mon imprimante imprime plus", "savRetrait"],
  ["fr", "mon écran de pc a un pixel mort", "savRetrait"],
  ["fr", "je voudrais faire réparer ma console", "savRetrait"],
  ["fr", "j'ai reçu un mail ma commande est prête", "savRetrait"],
  ["fr", "je viens retirer une commande", "savRetrait"],
  ["fr", "c'est pour un retour", "savRetrait"],
  ["fr", "il y a un souci avec ma trottinette", "savRetrait"],
  ["fr", "ma Switch a une manette qui drift", "savRetrait"],
  ["fr", "mon téléphone chauffe trop", "savRetrait"],
  ["fr", "mon ordinateur rame", "savRetrait"],
  ["fr", "j'ai cassé l'écran de ma tablette", "savRetrait"],
  ["en", "my phone screen is cracked", "savRetrait"],
  ["es", "mi portátil no enciende", "savRetrait"],
  ["fr", "je voudrais une coque pour mon iPhone 15", "apple"],
  ["fr", "un chargeur pour MacBook", "apple"],
  ["fr", "des AirPods Pro deux", "apple"],
  ["fr", "l'iPhone dix-sept pro", "apple"],
  ["fr", "je cherche Mario Kart pour la Switch 2", "gaming"],
  ["fr", "une manette de PS cinq", "gaming"],
  ["fr", "il vous reste des PS5", "gaming"],
  ["fr", "un jeu pour mon neveu sur Switch", "gaming"],
  ["fr", "des boosters Pokémon", "escalier"],
  ["fr", "un LEGO Star Wars", "escalier"],
  ["fr", "une enceinte pour la plage", "audio"],
  ["fr", "un casque Sony", "audio"],
  ["fr", "une barre de son pour ma télé", "audio"],
  ["fr", "des écouteurs pour le sport", "audio"],
  ["fr", "une télé pas trop grande pour la chambre", "tv"],
  ["fr", "un vidéo projecteur", "tv"],
  ["fr", "un sèche-cheveux", "electromenager"],
  ["fr", "un rasoir pour homme", "electromenager"],
  ["fr", "une machine Nespresso", "electromenager"],
  ["fr", "un aspirateur robot qui lave", "electromenager"],
  ["fr", "un grille-pain", "electromenager"],
  ["fr", "un ventilateur", "electromenager"],
  ["fr", "un ordinateur portable pour ma fille", "pcwindows"],
  ["fr", "un PC pour faire de la bureautique", "pcwindows"],
  ["fr", "une clé USB", "informatique"],
  ["fr", "un câble pour brancher mon ordi à la télé", "informatique"],
  ["fr", "un appareil photo pour les vacances", "photo"],
  ["fr", "une GoPro", "photo"],
  ["fr", "un casque pour trottinette", "trottinettes"],
  ["fr", "une montre qui mesure le sommeil", "objets"],
  ["fr", "une caméra pour surveiller mon chien", "objets"],
  ["fr", "une tablette pour ma grand-mère", "tablettes"],
  ["fr", "un jeu de société pour 4 joueurs", "jeuxSociete"],
  ["fr", "un puzzle", "jeuxSociete"],
  ["fr", "où sont les caisses s'il vous plaît", "caisse"],
  ["fr", "je voudrais la carte fidélité", "adhesion"],
  ["fr", "des cartouches pour Epson", "cartouches"],
  ["fr", "une liseuse", "liseuses"],
  ["fr", "le dernier Astérix", "editorial"],
  // …mais une phrase d'achat qui contient « pas », « plus » ou « casse » reste un achat
  ["fr", "un chargeur qui charge plus vite pour iPhone", "apple"],
  ["fr", "une batterie qui tient plus longtemps", "telephonie"],
  ["fr", "une télé pas chère", "tv"],
  ["fr", "un grille-pain", "electromenager"],
  ["fr", "un casse-tête", "jeuxSociete"],
  ["fr", "une enceinte qui marche bien", "audio"],
  ["fr", "un ordinateur qui rame pas pour mes études", "pcwindows"],
  ["fr", "ça tombe bien je cherche un téléphone", "telephonie"],
  ["fr", "je cherche une manette pas trop chère", "gaming"],
  ["fr", "je voudrais changer d'iPhone", "apple"],
  ["fr", "un téléphone qui ne coûte pas cher", "telephonie"],
  ["fr", "un casque qui isole bien du bruit", "audio"],
  ["fr", "un aspirateur qui aspire plus fort", "electromenager"],
];

// Questions pratiques : elles doivent passer avant les rayons.
const infoCases = [
  ["fr", "vous êtes ouvert jusqu'à quelle heure", "hours"],
  ["fr", "quels sont vos horaires", "hours"],
  ["fr", "vous êtes ouvert le dimanche", "hours"],
  ["fr", "où sont les toilettes", "toilets"],
  ["fr", "je peux me garer où", "parking"],
  ["en", "what time do you close", "hours"],
  ["en", "where is the restroom", "toilets"],
  ["es", "dónde están los baños", "toilets"],
  ["es", "a qué hora cierran", "hours"],
  // Pas de gros électroménager ici : le plus grand appareil est l'aspirateur balai.
  ["fr", "un lave-linge", "largeAppliances"],
  ["fr", "un frigo", "largeAppliances"],
  ["fr", "une machine à laver", "largeAppliances"],
  ["en", "a washing machine", "largeAppliances"],
  ["es", "una lavadora", "largeAppliances"],
  ["fr", "mon colis est ouvert", null],
  // Ascenseur (réservé aux personnes qui en ont besoin)
  ["fr", "il y a un ascenseur ?", "elevator"],
  ["fr", "je suis en fauteuil roulant", "elevator"],
  ["en", "is there a lift", "elevator"],
  ["es", "¿hay ascensor?", "elevator"],
  ["fr", "un fauteuil gamer", null]
];

// Demandes vagues : Jeanne pose une question (valeur = premier mot vague de la question),
// sauf si la phrase précise déjà (valeur = rayon).
const clarifyCases = [
  ["fr", "un casque", "?casque"],
  ["fr", "je cherche un casque pour mon fils", "?casque"],
  ["fr", "un casque JBL", "audio"],
  ["fr", "un casque pour jouer", "accessoiresGaming"],
  ["fr", "casque gamer", "accessoiresGaming"],
  ["fr", "un chargeur", "?chargeur"],
  ["fr", "un chargeur Samsung", "telephonie"],
  ["fr", "un chargeur d'iPhone", "apple"],
  ["fr", "un câble", "?câble"],
  ["fr", "un câble pour ma télé", "informatique"],
  ["fr", "un écran", "?écran"],
  ["fr", "mon écran est cassé", "savRetrait"],
  ["fr", "une tablette", "?tablette"],
  ["fr", "un ordinateur", "?ordinateur"],
  ["fr", "un ordinateur pour jouer", "accessoiresGaming"],
  ["fr", "un jeu", "?jeu"],
  ["fr", "un jeu de société", "jeuxSociete"],
  ["fr", "une carte", "?carte"],
  ["fr", "une carte cadeau", "caisse"],
  ["fr", "un aspirateur", "?aspirateur"],
  ["fr", "un aspirateur robot", "electromenager"],
  ["fr", "une machine à café", "?machine à café"],
  ["en", "a charger", "?chargeur"],
  ["fr", "un Sony", "?sony"],
  ["fr", "je cherche du Philips", "?philips"],
  ["fr", "une télé Sony", "tv"],
  ["fr", "un rasoir Philips", "electromenager"],
  ["es", "una batería", "?batterie"]
];
// Réponses du client à la question (au micro) : [mot vague, réponse, rayon choisi]
const answerCases = [
  ["un casque", "pour écouter de la musique", "audio"],
  ["un casque", "c'est pour jouer", "accessoiresGaming"],
  ["un casque", "pour mon vélo", "trottinettes"],
  ["un chargeur", "c'est pour un Samsung", "telephonie"],
  ["une tablette", "un iPad", "apple"],
  ["une carte", "une carte cadeau", "caisse"],
  ["une machine à café", "à capsules", "electromenager"],
  ["un casque", "je ne sais pas", null]
];
// Précommandes et produits à venir
const upcomingCases = [
  ["fr", "je veux précommander GTA 6", "gaming"],
  ["fr", "l'iPhone dix-huit", "apple"],
  ["fr", "le Galaxy S26 Ultra", "telephonie"],
  ["fr", "la PS6", "gaming"]
];
// Demandes sans produit précis : un vendeur conseillera mieux.
const intentCases = [
  ["fr", "un cadeau pour mon fils de 10 ans", "human"],
  ["fr", "je cherche une idée cadeau", "human"],
  ["fr", "bonjour", "hello"],
  ["fr", "merci beaucoup", "thanks"],
  ["fr", "j'ai besoin d'un conseil", "human"],
  ["fr", "je voudrais parler à quelqu'un", "human"],
  ["en", "a gift idea", "human"]
];

let failures = 0;
for (const [lang, text, expected] of infoCases) {
  const got = findInfo(text);
  const ok = got === expected;
  if (!ok) failures++;
  console.log(`${ok ? "✓" : "✗"} [${lang}] ${text} → ${got}${ok ? "" : `   (attendu : ${expected})`}`);
}
for (const [lang, text, expected] of intentCases) {
  const got = findZone(text, lang) ? "rayon " + findZone(text, lang) : findIntent(text);
  const ok = got === expected;
  if (!ok) failures++;
  console.log(`${ok ? "✓" : "✗"} [${lang}] ${text} → ${got}${ok ? "" : `   (attendu : ${expected})`}`);
}
for (const [lang, text, expected] of clarifyCases) {
  const match = findZoneDetailed(text, lang);
  const question = findClarify(text, match);
  const got = question ? "?" + question.words.fr[0] : match && match.id;
  const ok = got === expected;
  if (!ok) failures++;
  console.log(`${ok ? "✓" : "✗"} [${lang}] ${text} → ${got}${ok ? "" : `   (attendu : ${expected})`}`);
}
for (const [first, answer, expected] of answerCases) {
  const question = findClarify(first, findZoneDetailed(first, "fr"));
  const option = question && pickClarifyOption(answer, question);
  const got = option ? option.zone : null;
  const ok = got === expected;
  if (!ok) failures++;
  console.log(`${ok ? "✓" : "✗"} [fr] ${first} → « ${answer} » → ${got}${ok ? "" : `   (attendu : ${expected})`}`);
}
for (const [lang, text, expected] of [...upcomingCases, ...cases]) {
  const got = findZone(text, lang);
  const ok = got === expected;
  if (!ok) failures++;
  console.log(`${ok ? "✓" : "✗"} [${lang}] ${text} → ${got}${ok ? "" : `   (attendu : ${expected})`}`);
}
const total = cases.length + infoCases.length + intentCases.length + clarifyCases.length + answerCases.length + upcomingCases.length;
console.log(`\n${total - failures}/${total} réussis`);
process.exit(failures ? 1 : 0);
